// The homecoming's scenes at the end of a family's video (request 2026-09-29 — the homecoming's scenes, items 1 and 2): the two
// small things Astra's library has nothing of, for public/flashback.js `drawYard` (scenes drawn over the whole 854 by 480 video, a
// person about 130 px tall). Everything else in those scenes is hers: her cast in their delivered poses (the seated rest at the
// table, kneeling at the marker, carrying and notching for the new house, the elder holding out a purse for the land agent), her
// cabins, her burned cabin and the house going up, her table and her trees.
//
//   grave-marker      a plain wooden headboard on a low mound of earth, a few wildflowers: the family remembering its dead, dignified
//                     and quiet (no text on it, no body, no coffin - the dead of the war were not brought home).
//   coins-and-paper   a few silver coins in a stack and loose, a folded paper (the bill of sale), and a small leather purse, to lie on
//                     her `home-table` while the head of household counts what the family has left.
//
// Sized as the lone parent's scenes' pieces are: `logicalHeight` 300 is a grown person's height at the frame's own scale, so the
// page draws each with the height it gives a person and it stands at its true size beside them. Temporary, like every Claude frame:
// Astra's frame of the same name replaces each the moment it is registered.
export const AREA = 'places';
export const DATE = '2026-09-29';
const REQUEST = 'Request 2026-09-29 — the homecoming\'s scenes';
const INK = '#3d3222';

/** A wooden marker on a low mound, a person's logical height (300) to the frame: the board about four feet high. */
function graveMarker() {
  const W = 300, H = 300, ground = 286;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <!-- grave-marker: a wooden marker on a low mound, a few wildflowers. Claude-drawn stand-in (temporary: replace with Astra's grave-marker).
       Generated by scripts/claude-art/areas/homecoming.mjs; do not hand-edit. -->
  <g stroke-linejoin="round" stroke-linecap="round">
    <ellipse cx="150" cy="${ground - 4}" rx="104" ry="15" fill="#6d5a3e" opacity="0.35"/>
    <path d="M 52 ${ground - 2} C 70 ${ground - 30} 230 ${ground - 30} 248 ${ground - 2} Z" fill="#8a6c48" stroke="${INK}" stroke-width="3"/>
    <path d="M 70 ${ground - 8} C 100 ${ground - 22} 200 ${ground - 22} 232 ${ground - 8}" fill="none" stroke="#6e5436" stroke-width="2" opacity="0.7"/>
    <path d="M 128 ${ground - 18} L 128 150 Q 150 128 172 150 L 172 ${ground - 18} Z" fill="#a4815a" stroke="${INK}" stroke-width="3.5"/>
    <path d="M 140 160 L 140 ${ground - 24} M 156 152 L 156 ${ground - 26} M 164 170 C 162 190 166 210 163 240" fill="none" stroke="#7d5f3d" stroke-width="1.6" opacity="0.8"/>
    <path d="M 128 ${ground - 18} L 172 ${ground - 18}" stroke="#5c4629" stroke-width="3"/>
    <g stroke="#4f6e32" stroke-width="2">
      <path d="M 92 ${ground - 12} L 88 ${ground - 34}"/><path d="M 104 ${ground - 14} L 106 ${ground - 40}"/><path d="M 196 ${ground - 14} L 194 ${ground - 38}"/>
      <path d="M 210 ${ground - 11} L 214 ${ground - 32}"/><path d="M 118 ${ground - 16} L 114 ${ground - 30}"/><path d="M 184 ${ground - 16} L 188 ${ground - 30}"/>
    </g>
    <g stroke="${INK}" stroke-width="1.4">
      <circle cx="88" cy="${ground - 36}" r="6" fill="#e8c93e"/><circle cx="106" cy="${ground - 42}" r="6" fill="#f3efe2"/><circle cx="114" cy="${ground - 32}" r="5" fill="#d98cb3"/>
      <circle cx="194" cy="${ground - 40}" r="6" fill="#e8c93e"/><circle cx="214" cy="${ground - 34}" r="6" fill="#9a7ac0"/><circle cx="188" cy="${ground - 32}" r="5" fill="#f3efe2"/>
    </g>
    <path d="M 60 ${ground - 4} q 4 -10 8 0 M 232 ${ground - 4} q 4 -10 8 0 M 76 ${ground - 12} q 3 -8 6 0 M 220 ${ground - 12} q 3 -8 6 0" fill="none" stroke="#5f7d3a" stroke-width="2"/>
  </g>
</svg>
`;
  return { svg, anchorX: 0.5, anchorY: +((ground) / H).toFixed(4), logicalHeight: 300 };
}

/** Coins, a paper and a purse, lying on a table top, at a person's scale (300): about a foot across. */
function coinsAndPaper() {
  const W = 180, H = 90, ground = 82;
  const coin = (x, y) => `<ellipse cx="${x}" cy="${y}" rx="11" ry="4.5" fill="#d6d6cf" stroke="${INK}" stroke-width="1.6"/><ellipse cx="${x}" cy="${y - 1}" rx="7" ry="2.4" fill="none" stroke="#9c9c94" stroke-width="1"/>`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <!-- coins-and-paper: silver coins, a folded bill of sale and a purse on a table top. Claude-drawn stand-in (temporary: replace with Astra's coins-and-paper).
       Generated by scripts/claude-art/areas/homecoming.mjs; do not hand-edit. -->
  <g stroke-linejoin="round" stroke-linecap="round">
    <path d="M 14 ${ground - 18} L 78 ${ground - 36} L 96 ${ground - 12} L 30 ${ground + 4} Z" fill="#f1e8cf" stroke="${INK}" stroke-width="2"/>
    <path d="M 46 ${ground - 27} L 62 ${ground - 5}" stroke="#b9a77e" stroke-width="1.5"/>
    <path d="M 26 ${ground - 16} L 70 ${ground - 29} M 30 ${ground - 10} L 74 ${ground - 23} M 34 ${ground - 4} L 60 ${ground - 12}" stroke="#8c7a58" stroke-width="1.2" opacity="0.8"/>
    ${coin(128, ground - 4)}${coin(128, ground - 10)}${coin(128, ground - 16)}${coin(128, ground - 22)}${coin(150, ground - 2)}${coin(108, ground + 1)}
    <path d="M 150 ${ground - 12} C 142 ${ground - 26} 148 ${ground - 44} 160 ${ground - 44} C 172 ${ground - 44} 176 ${ground - 26} 168 ${ground - 12} Z" fill="#8a5a32" stroke="${INK}" stroke-width="2"/>
    <path d="M 152 ${ground - 38} C 158 ${ground - 34} 164 ${ground - 34} 170 ${ground - 38}" fill="none" stroke="#caa36a" stroke-width="2"/>
  </g>
</svg>
`;
  return { svg, anchorX: 0.5, anchorY: +((ground) / H).toFixed(4), logicalHeight: 300 };
}

export const SHEETS = {
  'claude-homecoming-marker': { cell: { w: 300, h: 300 }, columns: 1, request: REQUEST,
    replaceWith: 'item 1: prop contract, transparent, anchored at its base, a person\'s height as its logical height',
    frames: [{ name: 'grave-marker', height: 0.45, compare: [['rust-idle-e', 1], ['home-table', 0.68]], draw: graveMarker,
      prompt: 'A plain wooden grave marker set up by a family on its own land in 1836: a rounded-top board of weathered pine, about four feet high, with no words or symbol on it, standing at the head of a low mound of bare earth, a few yellow, white and pink wildflowers laid on the mound and growing at its edge. Quiet and dignified, never frightening; no body, no coffin, no text. Three-quarter view at the scale of the people who stand beside it; warm hand-drawn storybook style, dark olive-brown outline, flat shade, transparent ground.' }] },
  'claude-homecoming-coins': { cell: { w: 180, h: 90 }, columns: 1, request: REQUEST,
    replaceWith: 'item 2: prop contract, transparent, anchored at its base, laid on the table top (`home-table`)',
    frames: [{ name: 'coins-and-paper', height: 0.12, compare: [['home-table', 0.68], ['rust-idle-e', 1]], draw: coinsAndPaper,
      prompt: 'What a family counts at the table after the war: a short stack of silver reales and two loose coins, a folded sheet of paper (a bill of sale) with lines of handwriting too small to read, and a small drawstring leather purse, lying together on a table top. At the scale of a person seated at the table; warm hand-drawn storybook style, dark olive-brown outline, flat shade, transparent ground, no legible text.' }] },
};
export const CLIPS = {};
