// The house plot's remaining pieces (area E of docs/CLAUDE_ART_PLAN.md: E2, E3, E4), drawn to join Astra's house modules
// (docs/ART_DELIVERY_2026-09-15-HOUSE-MODULES.md) at her anchors, seats and ground corners.
//
// **Why these are cut from her own sheet.** A piece here is laid against one of hers in the same house - a pen's back walls
// under her roof, the roof between two of her pens' roofs, a chimney against her walls - and a flatter, simpler hand beside
// her painted logs would show every seam. So where a piece is her picture seen another way, it is made from her own pixels:
// `house-modules.png` placed in the SVG and re-cut. A pen seen from behind is her pen with the door filled in with her own
// logs, moved along their own courses (translated along the logs' slope, measured by self-similarity: 0.28-0.33); the roof
// between two pens is the middle of her roof repeated along its ridge (a translation along the ridge maps a gable roof onto
// itself), with neither gable end nor end pole. Where a piece is new - the pens seen end-on, the jacal, the shed's frame, the
// double chimney, the floor and loft - it is drawn in her projection (`PEN` below, read off her full walls) and laid with
// her own boards, logs, stone and mud as textures, outlined in her ink. Her files are only read
// (scripts/build-claude-standins.mjs `resolveLibraryImages`).
//
// Every frame is drawn at her pixel scale and carries `logicalHeight` equal to the height of the frame of hers it goes
// with, so `drawLogPen`'s arithmetic (every stage at the full walls' pixel scale) holds with no special case; seats and
// ground corners are hers where the silhouette is hers, and computed from `PEN` where it is new.
//
// Temporary, like every Claude frame: Astra's frame of the same name replaces each the moment it is registered.
import { readFileSync } from 'node:fs';
import { LINE } from '../kit/style.mjs';

export const AREA = 'places';
export const DATE = '2026-09-28';

const ASTRA = JSON.parse(readFileSync(new URL('../../../public/assets/frontier-v1/atlas.json', import.meta.url), 'utf8'));
const f2 = v => Math.round(v * 100) / 100;
const P = pts => pts.map(([x, y]) => `${f2(x)},${f2(y)}`).join(' ');
const INK = LINE.ink;

/** Her frame by name, with the web path of its sheet. */
export function her(name) {
  const frame = ASTRA.frames[name];
  if (!frame) throw new Error(`house-pieces: Astra's atlas has no ${name}`);
  const sheet = ASTRA.sheets[frame.sheet];
  return { ...frame, name, href: `/assets/frontier-v1/${sheet.image}`, sheetW: sheet.width, sheetH: sheet.height };
}

/** A drawing of one frame: collects SVG and defs, keeps ids unique on the sheet. */
class Canvas {
  constructor(name, w, h) { this.name = name; this.w = w; this.h = h; this.parts = []; this.defs = []; this.n = 0; }
  id(what) { return `${this.name}-${what}-${this.n++}`; }
  clip(points) { const id = this.id('clip'); this.defs.push(`<clipPath id="${id}"><polygon points="${P(points)}"/></clipPath>`); return id; }
  clipRect(x, y, w, h) { const id = this.id('rect'); this.defs.push(`<clipPath id="${id}"><rect x="${f2(x)}" y="${f2(y)}" width="${f2(w)}" height="${f2(h)}"/></clipPath>`); return id; }
  /** Her frame's pixels with its top-left at (ox, oy), cut to its own box so nothing of a neighbour comes with it. */
  image(frame, ox, oy, { transform = '' } = {}) {
    const rect = this.clipRect(ox, oy, frame.w, frame.h);
    return `<g${transform ? ` transform="${transform}"` : ''}><g clip-path="url(#${rect})"><image href="${frame.href}" x="${f2(ox - frame.x)}" y="${f2(oy - frame.y)}" width="${frame.sheetW}" height="${frame.sheetH}" preserveAspectRatio="none"/></g></g>`;
  }
  /** Her frame drawn whole at (ox, oy). */
  place(frame, ox, oy) { this.parts.push(this.image(frame, ox, oy)); }
  /**
   * A patch of her frame (placed at ox, oy) copied `(dx, dy)` onto the region `target` (points in this frame): what shows
   * inside `target` is her picture from `(dx, dy)` further along.
   */
  patch(frame, ox, oy, [dx, dy], target) {
    const clip = this.clip(target);
    this.parts.push(`<g clip-path="url(#${clip})">${this.image(frame, ox, oy, { transform: `translate(${f2(-dx)} ${f2(-dy)})` })}</g>`);
  }
  line(points, { width = LINE.inner, colour = INK, opacity } = {}) {
    this.parts.push(`<polyline points="${P(points)}" fill="none" stroke="${colour}" stroke-width="${width}" stroke-linecap="round" stroke-linejoin="round"${opacity != null ? ` opacity="${opacity}"` : ''}/>`);
  }
  raw(svg) { this.parts.push(svg); }
  svg(note) {
    return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${this.w}" height="${this.h}" viewBox="0 0 ${this.w} ${this.h}">
  <!-- ${this.name}: ${note}
       Claude-made stand-in (temporary: replace with Astra's ${this.name}). Generated by scripts/claude-art/areas/house-pieces.mjs from
       Astra's own house-modules pixels where it is her picture seen another way; do not hand-edit. -->
  <defs>${this.defs.join('')}</defs>
  <g>${this.parts.join('')}</g>
</svg>
`;
  }
}

// ---------------------------------------------------------------------------------------------------------------- E2
// The pen from behind: the gable toward the viewer without its door. The house-modules pen stands corner-on, the door in the
// left-front gable and a window in the right-front long side. Turned half round, the same silhouette shows the other gable
// (no door) on the left and the other long side on the right: so the picture is hers with the doorway filled with her own
// logs - the door is in the gable now behind the walls, as the request's first drawing has it. The window stays (a pen
// with a window in each long side). The sill is the same from either side and is hers, registered under the back name so a
// pen's stages go together.
//
// Each fill is a patch of the same wall's plain logs moved along their courses: the door's courses are one straight face,
// so a patch moved by (dx, dx x slope) lands log on log. Where her two sides of a doorway are not on one course (her right
// jamb's logs sit lower than her left's), the fill takes the right side's and meets the left at its jamb.
//
// A fill runs from x0 to x1 in narrow upright strips, each taken from the plain logs `src` (the next strip from the next
// logs, so the grain runs on), moved along the courses' `slope`; `corr` lifts the courses at each end so they meet her logs
// on both sides (her right side's courses sit a few pixels lower than her left's carried straight on), and `top` and
// `bottom` are the wall's edges at x0 and x1. Measured on a four-times grid of her frames.
const BACK = {
  round: {
    'full-walls': { from: 'house-round-full-walls', fill: { x0: 66, x1: 127, src: [128, 166], slope: 0.3, corr: [0, 0], top: [124, 143], bottom: [215, 243] } },
    'low-walls': { from: 'house-round-low-walls', fill: { x0: 84, x1: 152, src: [152, 192], slope: 0.2, corr: [7.4, 0], top: [92, 114], bottom: [172, 190] } },
    sill: { from: 'house-round-sill' },
  },
  hewn: {
    'full-walls': { from: 'house-hewn-full-walls', fill: { x0: 68, x1: 122, src: [124, 156], slope: 0.33, corr: [0, 0], top: [128, 148], bottom: [224, 251] } },
    'low-walls': { from: 'house-hewn-low-walls', fill: { x0: 84, x1: 150, src: [150, 191], slope: 0.23, corr: [5, 0], top: [94, 110], bottom: [169, 187.5] } },
    sill: { from: 'house-hewn-sill' },
  },
};
const STRIP = 4;
function fillCourses(c, frame, { x0, x1, src: [a, b], slope, corr, top, bottom }) {
  const at = ([y0, y1], x) => y0 + (y1 - y0) * (x - x0) / (x1 - x0);
  for (let x = x0; x < x1; x += STRIP) {
    const t = (x - x0) / (x1 - x0), from = a + t * (b - a - STRIP), dx = from - x, dy = slope * dx + corr[0] + (corr[1] - corr[0]) * t;
    const xe = Math.min(x1, x + STRIP) + 0.6; // a hair of overlap so no hairline of ground shows between strips
    c.patch(frame, 0, 0, [dx, dy], [[x, at(top, x)], [xe, at(top, xe)], [xe, at(bottom, xe)], [x, at(bottom, x)]]);
  }
  // `bottom` lies just under the wall's foot, so each strip keeps her own outline along the bottom of its logs.
}

function backPen(material, stage) {
  const spec = BACK[material][stage], frame = her(spec.from), name = `house-${material}-back-${stage}`;
  const c = new Canvas(name, frame.w, frame.h);
  c.place(frame, 0, 0);
  if (spec.fill) fillCourses(c, frame, spec.fill);
  return {
    svg: c.svg(stage === 'sill' ? `Astra's ${spec.from} as it stands: a sill is the same from behind` : `Astra's ${spec.from} with the doorway in the gable toward the viewer filled with her own logs, moved along their courses: the pen from behind`),
    anchorX: frame.anchorX, anchorY: frame.anchorY, logicalHeight: frame.h,
    ...(frame.seatX != null && { seat: [frame.seatX, frame.seatY] }), ...(frame.ground && { ground: frame.ground }),
  };
}

const backFrames = cell => ['round', 'hewn'].flatMap(material => ['sill', 'low-walls', 'full-walls'].map(stage => ({
  name: `house-${material}-back-${stage}`, draw: () => backPen(material, stage), height: 1.9, cell,
  compare: [[BACK[material][stage].from, 1.9], ['rust-idle-s', 1]],
  prompt: stage === 'sill'
    ? `A ${material}-log pen's sill seen from behind: the four sill logs of Astra's house-${material}-sill exactly as she drew them (a sill is the same from either side), registered as the back view so a pen drawn from behind goes through its stages in one set. Corner-on three-quarter view, north-up; her anchor and scale.`
    : `A ${material}-log pen's ${stage.replace('-', ' ')} seen from behind: Astra's house-${material}-${stage} with the doorway in the left-front gable filled in with her own ${material === 'round' ? 'round, bark-on' : 'hewn, squared'} logs, each course continued from the plain logs beside it (her pixels moved along the logs' own slope), so the gable toward the viewer is blank logs and the door is in the far gable behind the walls; the window in the long side stays. Same corner-on three-quarter view, scale, outline, anchor${stage === 'full-walls' ? ', wall-top seat and ground corners' : ''} as hers, so her roof seats on it and a chimney stands against its blank gable. Historical note: a single-pen cabin's chimney stood against one gable and its door was commonly in a long side or the other gable (HIST-GONZ-025); a blank gable behind a chimney is the ordinary arrangement.`,
})));

// ---------------------------------------------------------------------------------------------------------------- E3
// One roof over a two-pen house. Her roof is a gable roof on a ridge: moved along its ridge by any distance, its boards,
// poles and ridge log land on themselves. So the section between two pens is her roof's middle band - clear of both gable
// ends, their end poles, the ridge log's cut ends and the posts under the front gable - laid again and again along the
// ridge, each copy cut to the next band. The bands' edges run down the right slope along a board joint, so a seam is a
// joint. The section spans the same stretch of ridge as her whole roof (a pen's depth, sixteen feet) in the same box, so it
// seats on the walls exactly as her roof does, and laid over the gap between two pens it runs into both roofs.
//
// `STEP` is one band along the ridge in her roof's pixels, whole pixels so no copy is resampled: the ridge's direction read
// by self-similarity of the roof's middle (40 across, 33-34 up) at about one clapboard's width.
const JOIN = {
  'house-roof-join': { from: 'house-hewn-roof-finished' },
  'house-roof-join-partial': { from: 'house-round-roof-partial' },
};
const STEP = [18, -15];
/** The joint direction on the right slope (down it, toward the eave), along which the bands are cut. */
const JOINT_DIR = [0.62, 0.785];
/** Room round her roof's box: the section's front eave runs a little past where her gable's corner was. */
const MARGIN = 24;

/**
 * The ridge of her roof as a line in its frame's pixels: RIDGE in public/house-plot.js, read off the finished roof's ridge
 * log (it serves the partial roof within a degree). Kept here as data so the join frames carry their own ridge.
 */
const HER_RIDGE = [[110, 96], [205, 12]];

function roofJoin(name, { hole, span, under, over, bottom = 0 } = {}) {
  const spec = JOIN[name] || JOIN['house-roof-join'], frame = her(spec.from), m = MARGIN;
  const c = new Canvas(name, frame.w + 2 * m, frame.h + 2 * m + bottom);
  // p = origin + s * STEP + t * JOINT_DIR: s counts bands along the ridge, t pixels down the joints.
  const [ux, uy] = STEP, [jx, jy] = JOINT_DIR, det = ux * jy - uy * jx;
  const origin = [HER_RIDGE[0][0] + m, HER_RIDGE[0][1] + m];
  const s1 = ((HER_RIDGE[1][0] - HER_RIDGE[0][0]) * jy - (HER_RIDGE[1][1] - HER_RIDGE[0][1]) * jx) / det; // her ridge, in bands
  const bandFrom = Math.round(s1 * 0.4); // band 0: plain roof, clear of both gables' clutter
  const point = (s, t) => [origin[0] + s * ux + t * jx, origin[1] + s * uy + t * jy];
  const T0 = -260, T1 = 320; // far enough across to take the whole roof, both slopes and the eave blocks under it
  // The section's own ends: her roof's ridge with its overhang, or a share of it (`span`).
  const [S_LO, S_HI] = span ? [s1 * span[0], s1 * span[1]] : [-0.5, s1 + 0.5];
  if (under) under(c, point, S_LO, S_HI);
  const mask = hole ? hole(c, point) : null;
  const group = [];
  for (let k = -12; k <= 12; k++) {
    const lo = Math.max(S_LO, bandFrom + k), hi = Math.min(S_HI, bandFrom + k + 1);
    if (hi <= lo) continue;
    // Band 0's pixels moved k bands along the ridge; the cut edges overlap a hair so no gap opens between copies.
    const clip = c.clip([point(lo - 0.02, T0), point(hi + 0.02, T0), point(hi + 0.02, T1), point(lo - 0.02, T1)]);
    group.push(`<g clip-path="url(#${clip})">${c.image(frame, m, m, { transform: `translate(${k * ux} ${k * uy})` })}</g>`);
  }
  c.raw(`<g${mask ? ` mask="url(#${mask})"` : ''}>${group.join('')}</g>`);
  if (over) over(c, point, S_LO, S_HI);
  const fx = x => +(x / c.w).toFixed(4), fy = y => +(y / c.h).toFixed(4);
  const ridge = [point(S_LO, 0), point(S_HI, 0)].map(([x, y]) => [fx(x), fy(y)]);
  return {
    c, point, frame, m,
    svg: c.svg(`the middle of Astra's ${spec.from} repeated along its ridge: one roof section with no gable end and no end pole, to lie between two pens`),
    anchorX: fx(frame.anchorX * frame.w + m), anchorY: fy(frame.anchorY * frame.h + m), logicalHeight: frame.h,
    seat: [fx(frame.seatX * frame.w + m), fy(frame.seatY * frame.h + m)], extra: { ridge },
  };
}

const joinFrames = cell => Object.keys(JOIN).map(name => ({
  name, draw: () => roofJoin(name), height: 1.9, cell,
  compare: [[JOIN[name].from, 1.9], ['house-passage-roof', 1.9], ['rust-idle-s', 1]],
  prompt: `The clapboard roof over the open passage between two ${name.endsWith('partial') ? 'still-unchinked ' : ''}log pens, as one run of roof with them: Astra's ${JOIN[name].from} with both gable ends, the end poles, the ridge log's cut ends and the posts under the gable taken away, its middle - boards running from ridge to eave, the weight poles and the ridge log running through - repeated along the ridge (her pixels moved along the ridge, which maps a gable roof onto itself) over the same sixteen feet of ridge as her roof, so seated on a pen's walls as her roof is it covers the passage and runs into both pens' roofs without a seam. Exactly her pitch, ridge, eaves, scale and outline; the ridge line is given with the frame (\`ridge\`). Corner-on three-quarter view, transparent ground.`,
}));

// ---------------------------------------------------------------------------------------------------------------- the pen's projection
// New pieces are built in feet and projected as her pen is drawn. Her round full walls stand corner-on on a sixteen-foot
// square: the feet of the left, front and right corner posts are measured (`ground`, scripts/build-atlas-manifest.mjs) at
// (4.5, 195), (182.5, 250) and (297.5, 167) of her frame, so a foot along the door's face (a, left to front) is A and a foot
// along the long side (b, front to right, the way the ridge runs) is B. Up is 13 pixels a foot: her doorway is about 78
// pixels high and a door about six feet; her walls, 123 pixels at the front corner, are then about nine and a half feet.
// ceiling: an affine reading of a hand-drawn picture - her roof's ridge runs steeper than B (RIDGE in public/house-plot.js),
// so a new piece that meets her roof is placed by the roof's ridge, not by B (the double chimney's stack, below).
const PEN = Object.freeze({ L: [4.5, 195], A: [178 / 16, 55 / 16], B: [115 / 16, -83 / 16], Z: 13, wall: 9.5, ridge: 16 });
const proj = ([a, b, z], [ox, oy] = [0, 0]) => [PEN.L[0] + a * PEN.A[0] + b * PEN.B[0] + ox, PEN.L[1] + a * PEN.A[1] + b * PEN.B[1] - z * PEN.Z + oy];
const sub2 = (p, q) => [p[0] - q[0], p[1] - q[1]];
const add3 = (p, q) => [p[0] + q[0], p[1] + q[1], p[2] + q[2]];
const mul3 = (p, s) => [p[0] * s, p[1] * s, p[2] * s];

/**
 * Her materials, each a parallelogram of her sheet: `q0` its corner (sheet pixels), `u` the way the grain runs and `v`
 * across it, and how many feet each covers when laid on a new face at about her own pixel scale. Read on grids of her
 * frames (three times size, ten-pixel lines).
 */
const TEXTURES = (() => {
  const at = (name, [x, y]) => { const f = her(name); return [f.x + x, f.y + y]; };
  const t = (name, q0, u, v, feetU, feetV) => ({ href: her(name).href, sheetW: her(name).sheetW, sheetH: her(name).sheetH, q0: at(name, q0), u, v, feetU, feetV });
  return {
    // Bark-on logs from the door's face of her round walls, left of the door: the logs run along u.
    roundLogs: t('house-round-full-walls', [30, 96], [36, 11], [0, 96], 3.2, 7.4),
    hewnLogs: t('house-hewn-full-walls', [28, 98], [36, 12], [0, 100], 3.2, 7.7),
    // Planks of her passage floor's deck, running along u.
    planks: t('house-passage-floor', [14, 66], [100, -60], [124, 27], 12, 12),
    // Upright boards of her shed room's front, left of the door: the boards run down u.
    boards: t('house-shed-room', [52, 76], [0, 70], [96, 32], 5.4, 8.4),
    // Clapboards of her finished roof's right slope, running down the slope along u, the weight poles across them.
    roof: t('house-hewn-roof-finished', [150, 86], [74, 94], [54, -45], 10, 6),
    // A round post of her porch, running down u.
    post: t('house-porch', [165.5, 100], [0, 84], [8, 0], 7, 0.9),
    // Laid stone from the fire-box of her stone chimney.
    stone: t('house-chimney-stone', [20, 164], [48, 0], [0, 60], 4.2, 4.6),
    // Clay and sticks from her stick-and-mud chimney.
    mud: t('house-chimney-stick', [46, 92], [42, 0], [0, 80], 3.6, 6),
    // The jacal's woven sticks, its daub and its thatch (houses-settling).
    wattle: t('house-jacal-walls', [35, 56], [64, 0], [0, 46], 5.5, 4),
    daub: t('house-jacal', [36, 94], [58, 0], [0, 48], 5, 4.2),
    thatch: t('house-jacal', [62, 20], [0, 40], [160, 0], 4.5, 14),
  };
})();

/** The SVG affine matrix taking source vectors (su, sv) at q0 to screen vectors (pu, pv) at p0. */
function affine(q0, su, sv, p0, pu, pv) {
  const det = su[0] * sv[1] - su[1] * sv[0];
  const inv = [[sv[1] / det, -sv[0] / det], [-su[1] / det, su[0] / det]]; // rows of [su sv]^-1
  const a = pu[0] * inv[0][0] + pv[0] * inv[1][0], c = pu[0] * inv[0][1] + pv[0] * inv[1][1];
  const b = pu[1] * inv[0][0] + pv[1] * inv[1][0], d = pu[1] * inv[0][1] + pv[1] * inv[1][1];
  return [a, b, c, d, p0[0] - (a * q0[0] + c * q0[1]), p0[1] - (b * q0[0] + d * q0[1])];
}

/**
 * A modeller for one frame: faces in feet, laid with her materials and outlined in her ink. `offset` moves the projection
 * in the frame; `shade` darkens a face turned away from the light (her pens: the door's face lit, the long side darker).
 */
class Model {
  constructor(name, w, h, offset) { this.c = new Canvas(name, w, h); this.offset = offset; }
  /** A point in feet to pixels; a fourth number moves it that many pixels across (the stack set on her ridge). */
  p(pt) { const q = proj(pt, this.offset); if (pt.length > 3) q[0] += pt[3]; return q; }
  /**
   * A flat face: `corners` in feet (any polygon on one plane), laid with `texture` whose grain runs along `u3` and across
   * along `v3` (unit directions in feet) from `origin3`.
   */
  face(corners, texture, { origin3 = corners[0], u3, v3, shade = 0, outline = LINE.inner, tint } = {}) {
    const c = this.c, poly = corners.map(q => this.p(q));
    const clip = c.clip(poly);
    const tex = TEXTURES[texture];
    const o = this.p(origin3);
    const pu = sub2(this.p(add3(origin3, mul3(u3, tex.feetU))), o), pv = sub2(this.p(add3(origin3, mul3(v3, tex.feetV))), o);
    // How many tiles each way cover the face: the face's extent in the (u, v) grid.
    const det = pu[0] * pv[1] - pu[1] * pv[0];
    const uv = poly.map(([x, y]) => { const dx = x - o[0], dy = y - o[1]; return [(dx * pv[1] - dy * pv[0]) / det, (pu[0] * dy - pu[1] * dx) / det]; });
    const [i0, i1] = [Math.floor(Math.min(...uv.map(q => q[0]))), Math.ceil(Math.max(...uv.map(q => q[0])))];
    const [j0, j1] = [Math.floor(Math.min(...uv.map(q => q[1]))), Math.ceil(Math.max(...uv.map(q => q[1])))];
    const src = c.id('src');
    c.defs.push(`<clipPath id="${src}"><polygon points="${P([tex.q0, [tex.q0[0] + tex.u[0], tex.q0[1] + tex.u[1]], [tex.q0[0] + tex.u[0] + tex.v[0], tex.q0[1] + tex.u[1] + tex.v[1]], [tex.q0[0] + tex.v[0], tex.q0[1] + tex.v[1]]])}"/></clipPath>`);
    const tiles = [];
    for (let i = i0; i < i1; i++) for (let j = j0; j < j1; j++) {
      // A little over one tile each way, so the soft edge of a tile never lets ground show between tiles.
      const p0 = [o[0] + (i - 0.02) * pu[0] + (j - 0.02) * pv[0], o[1] + (i - 0.02) * pu[1] + (j - 0.02) * pv[1]];
      const m = affine(tex.q0, tex.u, tex.v, p0, pu.map(x => x * 1.04), pv.map(x => x * 1.04));
      tiles.push(`<g transform="matrix(${m.map(f2).join(' ')})"><g clip-path="url(#${src})"><image href="${tex.href}" x="0" y="0" width="${tex.sheetW}" height="${tex.sheetH}"/></g></g>`);
    }
    c.raw(`<g clip-path="url(#${clip})">${tiles.join('')}${tint ? `<polygon points="${P(poly)}" fill="${tint[0]}" opacity="${tint[1]}"/>` : ''}${shade ? `<polygon points="${P(poly)}" fill="#2a1a0c" opacity="${shade}"/>` : ''}</g>`);
    if (outline) c.raw(`<polygon points="${P(poly)}" fill="none" stroke="${INK}" stroke-width="${outline}" stroke-linejoin="round"/>`);
    return poly;
  }
  /** A box's three faces the camera sees (-b, +a, top), each laid with its material. */
  box([a0, b0, z0], [a1, b1, z1], texture, { top = texture, grain = 'b', shade = 0.2, topGrain = grain, tint } = {}) {
    const along = grain === 'a' ? [1, 0, 0] : grain === 'z' ? [0, 0, -1] : [0, 1, 0];
    // The face toward the lower left (b = b0): logs or boards run along a on it, or up it.
    this.face([[a0, b0, z0], [a1, b0, z0], [a1, b0, z1], [a0, b0, z1]], texture, { origin3: [a0, b0, z1], u3: grain === 'z' ? [0, 0, -1] : [1, 0, 0], v3: grain === 'z' ? [1, 0, 0] : [0, 0, -1], tint });
    // The face toward the lower right (a = a1), in shade.
    this.face([[a1, b0, z0], [a1, b1, z0], [a1, b1, z1], [a1, b0, z1]], texture, { origin3: [a1, b0, z1], u3: grain === 'z' ? [0, 0, -1] : [0, 1, 0], v3: grain === 'z' ? [0, 1, 0] : [0, 0, -1], shade, tint });
    // The top.
    const tu = topGrain === 'a' ? [1, 0, 0] : [0, 1, 0], tv = topGrain === 'a' ? [0, 1, 0] : [1, 0, 0];
    this.face([[a0, b0, z1], [a1, b0, z1], [a1, b1, z1], [a0, b1, z1]], top, { origin3: [a0, b0, z1], u3: tu, v3: tv, tint });
    void along;
  }
  /** An upright round post from z0 to z1 at (a, b), `r` feet thick: a lit front, a shaded side, a cut top. */
  post([a, b], z0, z1, r = 0.45) {
    const c = this.c, bottom = this.p([a, b, z0]), top = this.p([a, b, z1]), w = r * 2 * 11;
    const poly = [[top[0] - w / 2, top[1]], [top[0] + w / 2, top[1]], [bottom[0] + w / 2, bottom[1]], [bottom[0] - w / 2, bottom[1]]];
    const clip = c.clip(poly), tex = TEXTURES.post;
    const m = affine(tex.q0, tex.u, tex.v, poly[0], [0, bottom[1] - top[1]], [w, 0]);
    c.raw(`<g clip-path="url(#${clip})"><g transform="matrix(${m.map(f2).join(' ')})"><image href="${tex.href}" x="0" y="0" width="${tex.sheetW}" height="${tex.sheetH}"/></g></g>`);
    c.raw(`<polygon points="${P(poly)}" fill="none" stroke="${INK}" stroke-width="${LINE.inner}" stroke-linejoin="round"/>`);
    c.raw(`<ellipse cx="${f2(top[0])}" cy="${f2(top[1])}" rx="${f2(w / 2)}" ry="${f2(w / 4)}" fill="#c89a5c" stroke="${INK}" stroke-width="${LINE.fine}"/>`);
  }
  /** A beam from p to q (feet), `r` feet thick, drawn as a round pole in her post's wood. */
  beam(p3, q3, r = 0.35) {
    const c = this.c, p = this.p(p3), q = this.p(q3), d = sub2(q, p), l = Math.hypot(...d), n = [-d[1] / l * r * 11, d[0] / l * r * 11];
    const poly = [[p[0] + n[0], p[1] + n[1]], [q[0] + n[0], q[1] + n[1]], [q[0] - n[0], q[1] - n[1]], [p[0] - n[0], p[1] - n[1]]];
    const clip = c.clip(poly), tex = TEXTURES.post;
    const m = affine(tex.q0, tex.u, tex.v, poly[0], sub2(poly[1], poly[0]), sub2(poly[3], poly[0]));
    c.raw(`<g clip-path="url(#${clip})"><g transform="matrix(${m.map(f2).join(' ')})"><image href="${tex.href}" x="0" y="0" width="${tex.sheetW}" height="${tex.sheetH}"/></g></g>`);
    c.raw(`<polygon points="${P(poly)}" fill="none" stroke="${INK}" stroke-width="${LINE.fine + 0.4}" stroke-linejoin="round"/>`);
  }
  /** A dark opening (a door, a flue, a loophole) on a face. */
  hole(corners, fill = '#2b1c12') { const poly = corners.map(q => this.p(q)); this.c.raw(`<polygon points="${P(poly)}" fill="${fill}" stroke="${INK}" stroke-width="${LINE.fine + 0.4}" stroke-linejoin="round"/>`); return poly; }
  svg(note) { return this.c.svg(note); }
}

/** The fractions of a point in a frame. */
const frac = (c, [x, y]) => [+(x / c.w).toFixed(4), +(y / c.h).toFixed(4)];
const WALLS = her('house-round-full-walls');
/** A pen-sized frame: her full walls' box, anchor, ground and scale, so a piece in it stands where her pen stands. */
const penFrame = (name, pad = [0, 0, 0, 0]) => {
  const [top, right, bottom, left] = pad;
  return { m: new Model(name, WALLS.w + left + right, WALLS.h + top + bottom, [left, top]), top, left };
};
const penNumbers = ({ m, top, left }, { seatZ } = {}) => {
  const c = m.c, at = (x, y) => [+(x / c.w).toFixed(4), +(y / c.h).toFixed(4)];
  return {
    anchorX: at(WALLS.anchorX * WALLS.w + left, 0)[0], anchorY: at(0, WALLS.anchorY * WALLS.h + top)[1], logicalHeight: WALLS.h,
    ground: { left: frac(c, m.p([0, 0, 0])), front: frac(c, m.p([16, 0, 0])), right: frac(c, m.p([16, 16, 0])) },
    ...(seatZ != null && { seat: frac(c, m.p([8, 8, seatZ])) }),
  };
};

// ---------------------------------------------------------------------------------------------------------------- E4: the jacal
// A jacal pen in the log pens' own projection and footprint, so it goes up by stages as they do and seats its roof the same
// way: posts set upright in a trench (`house-jacal-posts`), the walls woven with sticks between them and daubed with mud
// (`house-jacal-wattle`), and a thatched roof, hipped as her whole jacal's is (`house-jacal-thatch`). Laid with her own
// daub, wattle, posts and thatch from the houses-settling jacal. Research: HIST-GONZ notes a jacal as "posts set in the
// ground, walls of sticks and mud between, a roof of thatch" (sim/houseplot.mjs); Texas jacales were commonly of upright
// posts or pickets set in a trench and chinked or plastered with mud, roofed with thatch or tule. Wall height and pitch are
// read from her jacal and are not a documented measurement.
const JACAL = { wall: 7.5, door: [6.6, 10.4], doorHigh: 6.2, posts: [0, 4, 8, 12, 16], wallPosts: [0, 8, 16] };

function jacalPosts({ m }, { upTo = JACAL.wall, daub = false } = {}) {
  const { wall } = JACAL, every = daub ? JACAL.wallPosts : JACAL.posts;
  // Far walls first (their inner faces), then the near walls; posts at every four feet and at the door.
  const far = [...every.map(b => [0, b]), ...every.slice(1).map(a => [a, 16])];
  const near = [...every.map(a => [a, 0]).filter(([a]) => a < 16), ...every.map(b => [16, b])];
  if (!daub) {
    // The trench the posts are set in, dug round the square: turned earth.
    const trench = [[0, 0, 0], [16, 0, 0], [16, 16, 0], [0, 16, 0]].map(q => m.p(q));
    m.c.raw(`<polygon points="${P(trench)}" fill="none" stroke="${INK}" stroke-width="9" stroke-linejoin="round" opacity="0.8"/><polygon points="${P(trench)}" fill="none" stroke="#8a5f38" stroke-width="6" stroke-linejoin="round"/><polygon points="${P(trench)}" fill="none" stroke="#5e3f22" stroke-width="2" stroke-linejoin="round" stroke-dasharray="3 5"/>`);
  }
  if (daub) {
    // The far walls' inner faces: the a = 0 wall seen from inside (toward +a, in shade) and the b = 16 wall (toward -b).
    m.face([[0, 0, 0], [0, 16, 0], [0, 16, wall], [0, 0, wall]], 'daub', { origin3: [0, 0, wall], u3: [0, 1, 0], v3: [0, 0, -1], shade: 0.3 });
    m.face([[0, 16, 0], [16, 16, 0], [16, 16, wall], [0, 16, wall]], 'daub', { origin3: [0, 16, wall], u3: [1, 0, 0], v3: [0, 0, -1], shade: 0.12 });
  }
  for (const [a, b] of far.sort((p, q) => q[1] - p[1] || p[0] - q[0])) m.post([a, b], 0, upTo + 0.3, 0.55);
  if (daub) {
    const [d0, d1] = JACAL.door;
    // The door's face, with the doorway cut through it, and the long side with a small window.
    m.face([[0, 0, 0], [d0, 0, 0], [d0, 0, JACAL.doorHigh], [d1, 0, JACAL.doorHigh], [d1, 0, 0], [16, 0, 0], [16, 0, wall], [0, 0, wall]], 'daub', { origin3: [0, 0, wall], u3: [1, 0, 0], v3: [0, 0, -1] });
    m.hole([[d0, 0, 0], [d1, 0, 0], [d1, 0, JACAL.doorHigh], [d0, 0, JACAL.doorHigh]], '#3a2616');
    m.face([[16, 0, 0], [16, 16, 0], [16, 16, wall], [16, 0, wall]], 'daub', { origin3: [16, 0, wall], u3: [0, 1, 0], v3: [0, 0, -1], shade: 0.22 });
    m.hole([[16, 9, 3.6], [16, 11.5, 3.6], [16, 11.5, 5.4], [16, 9, 5.4]], '#2b1c12');
    // The wall plate along the tops.
    m.beam([0, 0, wall], [16, 0, wall], 0.3); m.beam([16, 0, wall], [16, 16, wall], 0.3);
  }
  const inDoor = ([a, b]) => b === 0 && a > JACAL.door[0] && a < JACAL.door[1];
  const nearPosts = [...near.filter(post => !inDoor(post)), [JACAL.door[0], 0], [JACAL.door[1], 0]].sort((p, q) => q[1] - p[1] || p[0] - q[0]);
  for (const [a, b] of nearPosts) m.post([a, b], 0, upTo + 0.3, 0.55);
  if (daub) m.beam([JACAL.door[0], 0, JACAL.doorHigh], [JACAL.door[1], 0, JACAL.doorHigh], 0.28);
}

function jacalWalls(stage) {
  const frame = penFrame(`house-jacal-${stage}`, [10, 6, 0, 6]);
  if (stage === 'posts') jacalPosts(frame);
  else jacalPosts(frame, { daub: true });
  return { svg: frame.m.svg(stage === 'posts' ? 'a jacal pen\'s posts set upright in the ground, in the log pens\' projection and footprint' : 'a jacal pen\'s walls, sticks woven between the posts and daubed with mud, in the log pens\' projection and footprint'),
    ...penNumbers(frame, { seatZ: stage === 'posts' ? null : JACAL.wall }) };
}

function jacalThatch() {
  const frame = penFrame('house-jacal-thatch', [40, 40, 10, 40]), { m } = frame;
  const e = 1.6, z0 = JACAL.wall - 0.5, zr = 13.6, r0 = 4.2, r1 = 11.8; // eaves out 1.6 ft and a little down; a short ridge along b
  const E = { a0: -e, a1: 16 + e, b0: -e, b1: 16 + e };
  const ridge0 = [8, r0, zr], ridge1 = [8, r1, zr];
  // The far (-a) slope shows only as a sliver past the ridge; then the long (+a) slope in shade, then the hipped end toward the viewer.
  m.face([[E.a0, E.b0, z0], [E.a0, E.b1, z0], ridge1, ridge0], 'thatch', { origin3: ridge0, u3: [-0.6, 0, -0.8], v3: [0, 1, 0], shade: 0.18 });
  m.face([[E.a1, E.b0, z0], [E.a1, E.b1, z0], ridge1, ridge0], 'thatch', { origin3: ridge0, u3: [0.6, 0, -0.8], v3: [0, 1, 0], shade: 0.16 });
  m.face([[E.a0, E.b0, z0], [E.a1, E.b0, z0], ridge0], 'thatch', { origin3: ridge0, u3: [0, -0.6, -0.8], v3: [1, 0, 0] });
  // The thatch's thickness at the eaves, cut square, as her jacal's is.
  const t = 0.8;
  m.face([[E.a1, E.b0, z0], [E.a1, E.b1, z0], [E.a1, E.b1, z0 - t], [E.a1, E.b0, z0 - t]], 'thatch', { origin3: [E.a1, E.b0, z0], u3: [0, 0, -1], v3: [0, 1, 0], shade: 0.3 });
  m.face([[E.a0, E.b0, z0], [E.a1, E.b0, z0], [E.a1, E.b0, z0 - t], [E.a0, E.b0, z0 - t]], 'thatch', { origin3: [E.a0, E.b0, z0], u3: [0, 0, -1], v3: [1, 0, 0], shade: 0.12 });
  // A rolled ridge of thatch.
  m.beam(ridge0, ridge1, 0.55);
  return { svg: m.svg('a thatched roof for a jacal pen, hipped as Astra\'s jacal\'s is, to seat on its walls'), ...penNumbers(frame, { seatZ: JACAL.wall }) };
}

const jacalFrames = () => [
  { name: 'house-jacal-posts', draw: () => jacalWalls('posts'), height: 1.9, compare: [['house-jacal-site', 1.9], ['house-round-sill', 1.9]],
    prompt: 'A jacal pen at its first stage: round posts cut and set upright in the ground at the corners, every four feet along the walls and either side of the doorway, sixteen feet square, in the log pens\' corner-on three-quarter view and footprint (Astra\'s house-modules projection), in Astra\'s own post wood from her jacal. Stands where her pen stands, on her full walls\' anchor. Transparent ground, no shadow.' },
  { name: 'house-jacal-wattle', draw: () => jacalWalls('wattle'), height: 1.9, compare: [['house-jacal-walls', 1.9], ['house-round-full-walls', 1.9]],
    prompt: 'A jacal pen\'s walls, finished: sticks woven between the upright posts and daubed with mud (Astra\'s own daub from her jacal laid on each face), a doorway in the gable toward the viewer where her log pen has its door, a small window in the long side, a pole wall plate along the tops; about seven and a half feet high. The log pens\' corner-on three-quarter view, footprint, anchor and wall-top seat, so the thatch seats on it as her roofs seat on her walls. Transparent ground, no shadow.' },
  { name: 'house-jacal-thatch', draw: jacalThatch, height: 1.9, compare: [['house-jacal', 1.9], ['house-hewn-roof-finished', 1.9]],
    prompt: 'A jacal pen\'s roof: grass thatch, hipped at the ends as Astra\'s whole jacal\'s roof is, a rolled ridge along the pen\'s long axis, the eaves standing out over the walls; laid with her own thatch. Seats on house-jacal-wattle by its seat as her roofs seat on her walls; corner-on three-quarter view. Transparent ground, no shadow.' },
];

/** A frame fitted round a piece: its corners in feet, room round them, and its ground anchor as a point in feet. */
function fitted(name, corners, anchor3, pad = 8) {
  const pts = corners.map(q => proj(q));
  const x0 = Math.min(...pts.map(p => p[0])), x1 = Math.max(...pts.map(p => p[0])), y0 = Math.min(...pts.map(p => p[1])), y1 = Math.max(...pts.map(p => p[1]));
  const m = new Model(name, Math.ceil(x1 - x0 + 2 * pad), Math.ceil(y1 - y0 + 2 * pad), [pad - x0, pad - y0]);
  const [ax, ay] = m.p(anchor3);
  return { m, anchorX: +(ax / m.c.w).toFixed(4), anchorY: +(ay / m.c.h).toFixed(4) };
}
const boxCorners = ([a0, b0, z0], [a1, b1, z1]) => [[a0, b0, z0], [a1, b0, z0], [a1, b1, z0], [a0, b1, z0], [a0, b0, z1], [a1, b0, z1], [a1, b1, z1], [a0, b1, z1]];

// ---------------------------------------------------------------------------------------------------------------- E4: the double chimney
// The saddlebag's one big chimney between its two pens (HIST-TEX-017; sim/houseplot.mjs `chimney-double`): a broad stone
// mass filling the eight feet between the near pen's back gable and the far pen's front gable, a fire-box opening into
// each pen, drawing up into one tall stack that rises through the ridge. Laid in Astra's own stone from her stone chimney.
// Its ground anchor is its front corner (the lowest point of its foot); `centre` is the middle of its foot - the point
// between the two gables on the pens' centre line, where `standChimneys` stands it - and `foot` its four foot corners. Saddlebag chimneys were built of stone or of sticks
// and clay; stone is drawn (her stone chimney's) and is an interpretation, not a record of any one house.
//
// Her roof's ridge runs steeper than the pen's long side (RIDGE in public/house-plot.js), so the stack is set where her
// roof's ridge is over the middle of the gap - 20 of her pixels left of straight up from the foot - and the join roof's
// opening for it (`house-roof-join-chimney`) is cut from the same outline.
const DOUBLE = { a: [4.6, 11.4], b: [16.2, 23.8], mass: 9.2, stack: { a: [6.3, 9.7], b: [17.4, 22.6], z: [9.2, 19.6] }, shift: -20 };
const WALLS_CENTRE = [(WALLS.ground.left[0] + WALLS.ground.right[0]) / 2 * WALLS.w, (WALLS.ground.left[1] + WALLS.ground.right[1]) / 2 * WALLS.h];
const WALLS_SEAT = [WALLS.seatX * WALLS.w, WALLS.seatY * WALLS.h];

/** The stack's outline, in pixels from the chimney's foot (the middle of the gap on the ground). */
function stackOutline() {
  const { a, b, z } = DOUBLE.stack, foot = proj([8, 20, 0]);
  const q = pt => { const [x, y] = proj(pt); return [x - foot[0] + DOUBLE.shift, y - foot[1]]; };
  // The silhouette of an upright box seen from here: bottom-left, bottom-front, bottom-right, top-right, top-back, top-left.
  return [q([a[0], b[0], z[0]]), q([a[1], b[0], z[0]]), q([a[1], b[1], z[0]]), q([a[1], b[1], z[1]]), q([a[0], b[1], z[1]]), q([a[0], b[0], z[1]])];
}

function doubleChimney() {
  const { a, b, mass, stack } = DOUBLE;
  const f = fitted('house-chimney-double', [...boxCorners([a[0], b[0], 0], [a[1], b[1], mass]), ...boxCorners([stack.a[0] - 2, stack.b[0], 0], [stack.a[1], stack.b[1], stack.z[1]])], [DOUBLE.a[1], DOUBLE.b[0], 0], 14);
  const { m } = f;
  // The mass between the pens: its long side toward the viewer's right, the shoulders drawing in to the stack.
  m.box([a[0], b[0], 0], [a[1], b[1], mass], 'stone', { shade: 0.22, grain: 'a' });
  const sh = 1.6;
  const d = DOUBLE.shift;
  m.face([[a[1], b[0], mass], [a[1], b[1], mass], [stack.a[1], stack.b[1], mass + sh, d], [stack.a[1], stack.b[0], mass + sh, d]], 'stone', { origin3: [a[1], b[0], mass], u3: [0, 1, 0], v3: [-0.7, 0, 0.7], shade: 0.16 });
  m.face([[a[0], b[0], mass], [a[1], b[0], mass], [stack.a[1], stack.b[0], mass + sh, d], [stack.a[0], stack.b[0], mass + sh, d]], 'stone', { origin3: [a[0], b[0], mass], u3: [1, 0, 0], v3: [0, 0.7, 0.7] });
  m.face([[a[0], b[0], mass], [stack.a[0], stack.b[0], mass + sh, d], [stack.a[0], stack.b[1], mass + sh, d], [a[0], b[1], mass]], 'stone', { origin3: [a[0], b[0], mass], u3: [0, 1, 0], v3: [0.7, 0, 0.7], shade: 0.05 });
  // The stack, set on her roof's ridge line.
  const save = m.offset; m.offset = [save[0] + DOUBLE.shift, save[1]];
  m.box([stack.a[0], stack.b[0], mass + sh], [stack.a[1], stack.b[1], stack.z[1]], 'stone', { shade: 0.24, grain: 'a' });
  // Two flues, one from each fire-box, dark in the stack's top.
  const zt = stack.z[1];
  m.hole([[6.8, 18.1, zt], [9.2, 18.1, zt], [9.2, 19.7, zt], [6.8, 19.7, zt]], '#231710');
  m.hole([[6.8, 20.3, zt], [9.2, 20.3, zt], [9.2, 21.9, zt], [6.8, 21.9, zt]], '#231710');
  m.offset = save;
  const c = m.c;
  return { svg: m.svg('the saddlebag house\'s double chimney between its two pens, in Astra\'s stone'), anchorX: f.anchorX, anchorY: f.anchorY, logicalHeight: WALLS.h,
    extra: { centre: frac(c, m.p([8, 20, 0])), foot: [[a[0], b[0]], [a[1], b[0]], [a[1], b[1]], [a[0], b[1]]].map(([aa, bb]) => frac(c, m.p([aa, bb, 0]))) } };
}

/** The join roof with an opening where the double chimney's stack stands through its ridge. */
function roofJoinChimney() {
  const frame = her(JOIN['house-roof-join'].from), mg = MARGIN;
  // Where the chimney's foot is in this frame: the roof is seated on a pen standing at the gap's middle, so the foot is the
  // roof's seat moved as the pen's ground centre is from its seat.
  const seat = [frame.seatX * frame.w + mg, frame.seatY * frame.h + mg];
  const foot = [seat[0] + WALLS_CENTRE[0] - WALLS_SEAT[0], seat[1] + WALLS_CENTRE[1] - WALLS_SEAT[1]];
  const outline = stackOutline().map(([x, y]) => [foot[0] + x, foot[1] + y]);
  const drawn = roofJoin('house-roof-join-chimney', { hole: (c, point) => {
    // Open where the stack stands above a line along the ridge a few pixels down the right slope (where the stack's front
    // comes up out of the boards); below that line the roof is in front of the stack and stays.
    const id = c.id('hole'), half = c.id('half'), a = point(-20, 6), b = point(20, 6);
    c.defs.push(`<clipPath id="${half}"><polygon points="${P([a, b, [b[0], -2000], [a[0], -2000]])}"/></clipPath>`);
    c.defs.push(`<mask id="${id}" maskUnits="userSpaceOnUse" x="0" y="0" width="${c.w}" height="${c.h}"><rect x="0" y="0" width="${c.w}" height="${c.h}" fill="white"/><polygon points="${P(outline)}" fill="black" clip-path="url(#${half})"/></mask>`);
    return id;
  } });
  return { ...drawn, extra: { ...drawn.extra, chimneyAt: frac(drawn.c, foot) } };
}

// ---------------------------------------------------------------------------------------------------------------- E4: shed frame, floor, loft
// The shed room framed and not yet boarded (`house-shed-frame`): sills, corner and middle posts, the plates and the rafters
// of its lean-to roof, in her shed room's orientation and size (sixteen feet along the door's face, eight deep, higher at the
// back where it meets the pen), so her `house-shed-room` replaces it in place when the room is finished. Her post wood.
// `logicalHeight` sizes it as the page draws her shed room (a foot of it the same on screen: hers is about 16 pixels a foot).
const SHED_LH = Math.round(her('house-shed-room').h * Math.hypot(...PEN.A) / 16.1);

function shedFrame() {
  const lo = 7, hi = 8.6;
  const f = fitted('house-shed-frame', [...boxCorners([0, -0.8, 0], [16, 8.3, hi + 0.4])], [16, 0, 0], 12), { m } = f;
  m.beam([0, 8, 0.3], [16, 8, 0.3], 0.35); m.beam([0, 0, 0.3], [0, 8, 0.3], 0.35);
  for (const a of [0, 8, 16]) m.post([a, 8], 0, hi, 0.4);
  m.beam([0, 8, hi], [16, 8, hi], 0.32);
  m.beam([16, 0, 0.3], [16, 8, 0.3], 0.35); m.beam([0, 0, 0.3], [16, 0, 0.3], 0.35);
  for (const a of [0, 4, 8, 12, 16]) m.beam([a, 8.3, hi + 0.2], [a, -0.8, lo - 0.1], 0.26);
  for (const a of [0, 8, 16]) m.post([a, 0], 0, lo, 0.4);
  m.beam([0, 0, lo], [16, 0, lo], 0.32);
  return { svg: m.svg('the shed room framed and not yet boarded'), anchorX: f.anchorX, anchorY: f.anchorY, logicalHeight: SHED_LH };
}

/** The puncheon floor inside a pen, registered to her full walls: drawn before the walls, it shows through the doorway. */
function penFloor() {
  const frame = penFrame('house-floor'), { m } = frame;
  m.face([[0.6, 0.6, 0.25], [15.4, 0.6, 0.25], [15.4, 15.4, 0.25], [0.6, 15.4, 0.25]], 'hewnLogs', { origin3: [0.6, 0.6, 0.25], u3: [0, 1, 0], v3: [1, 0, 0], outline: LINE.fine });
  return { svg: m.svg('a puncheon floor laid inside a pen'), ...penNumbers(frame) };
}

/** The loft in a pen: joists across under the roof, boards over the back half, and a ladder up; registered to her walls. */
function penLoft() {
  const frame = penFrame('house-loft', [4, 0, 0, 0]), { m } = frame, z = PEN.wall - 0.4;
  for (const b of [1.5, 4.5, 7.5]) m.beam([0.4, b, z], [15.6, b, z], 0.3);
  m.face([[0.5, 8.5, z + 0.3], [15.5, 8.5, z + 0.3], [15.5, 15.5, z + 0.3], [0.5, 15.5, z + 0.3]], 'planks', { origin3: [0.5, 8.5, z + 0.3], u3: [0, 1, 0], v3: [1, 0, 0] });
  m.face([[0.5, 8.5, z + 0.3], [15.5, 8.5, z + 0.3], [15.5, 8.5, z - 0.3], [0.5, 8.5, z - 0.3]], 'planks', { origin3: [0.5, 8.5, z], u3: [1, 0, 0], v3: [0, 0, -1], shade: 0.25 });
  // A ladder of two poles and rungs, from the floor up to the loft's edge.
  m.beam([11, 3.5, 0], [11, 8.3, z + 0.3], 0.18); m.beam([12.6, 3.5, 0], [12.6, 8.3, z + 0.3], 0.18);
  for (let t = 0.12; t < 1; t += 0.14) m.beam([11, 3.5 + 4.8 * t, (z + 0.3) * t], [12.6, 3.5 + 4.8 * t, (z + 0.3) * t], 0.12);
  return { svg: m.svg('a pen\'s loft: joists, a board floor over the back half and a ladder'), ...penNumbers(frame) };
}

// ---------------------------------------------------------------------------------------------------------------- E2: the end views
// The porch, the shed room, the passage's floor and its roof seen from their narrow ends, their long side running into the
// screen along the pen's other diagonal (the way its ridge runs): her pieces turned a quarter, built in the pen's projection
// in her own boards, planks, posts and clapboards, each sized to her piece of the same name as the page draws it (her
// pixels a foot: porch about 18, passage floor about 9 - read on her frames).
const PORCH_LH = Math.round(her('house-porch').h * Math.hypot(...PEN.A) / 18);
const PASSAGE_FLOOR_LH = Math.round(her('house-passage-floor').h * Math.hypot(...PEN.A) / 8.9);

function deck(m, [a0, b0], [a1, b1], z) {
  m.box([a0, b0, 0], [a1, b1, z], 'planks', { shade: 0.28, grain: 'a', top: 'planks', topGrain: 'a' });
}

function porchEnd() {
  const hiZ = 9, loZ = 7.6;
  const f = fitted('house-porch-end', boxCorners([-0.6, -0.8, 0], [8.8, 16.8, hiZ + 0.2]), [8, 0, 0], 10), { m } = f;
  m.post([0.6, 15.4], 1, hiZ);
  deck(m, [0, 0], [8, 16], 1.1);
  for (const b of [15.4, 8, 0.6]) m.post([7.4, b], 1.1, loZ);
  m.post([0.6, 0.6], 1.1, hiZ);
  m.beam([7.4, -0.6, loZ], [7.4, 16.6, loZ], 0.3);
  // The shed roof, falling from the pen's side to the porch's edge, boards running down it.
  m.face([[-0.6, -0.8, hiZ], [8.8, -0.8, loZ - 0.2], [8.8, 16.8, loZ - 0.2], [-0.6, 16.8, hiZ]], 'roof', { origin3: [-0.6, -0.8, hiZ], u3: [0.99, 0, -0.14], v3: [0, 1, 0] });
  m.face([[-0.6, -0.8, hiZ], [8.8, -0.8, loZ - 0.2], [8.8, -0.8, loZ - 0.7], [-0.6, -0.8, hiZ - 0.5]], 'planks', { origin3: [-0.6, -0.8, hiZ], u3: [1, 0, 0], v3: [0, 0, -1], shade: 0.1 });
  return { svg: m.svg('the porch seen from its end, its long side running into the screen'), anchorX: f.anchorX, anchorY: f.anchorY, logicalHeight: PORCH_LH };
}

function shedRoomEnd() {
  const hiZ = 8.6, loZ = 7;
  const f = fitted('house-shed-room-end', boxCorners([-0.5, -0.8, 0], [8.8, 16.8, hiZ + 0.4]), [8, 0, 0], 10), { m } = f;
  // The end toward the viewer, higher at the pen's side, with the door in it; the long side in shade.
  m.face([[0, 0, 0], [8, 0, 0], [8, 0, loZ], [0, 0, hiZ]], 'boards', { origin3: [0, 0, hiZ], u3: [0, 0, -1], v3: [1, 0, 0] });
  m.hole([[3, 0, 0], [5.6, 0, 0], [5.6, 0, 6.2], [3, 0, 6.2]], '#5a3d24');
  m.face([[8, 0, 0], [8, 16, 0], [8, 16, loZ], [8, 0, loZ]], 'boards', { origin3: [8, 0, loZ], u3: [0, 0, -1], v3: [0, 1, 0], shade: 0.24 });
  m.post([8, 0], 0, loZ, 0.35);
  m.face([[-0.5, -0.8, hiZ + 0.2], [8.8, -0.8, loZ - 0.2], [8.8, 16.8, loZ - 0.2], [-0.5, 16.8, hiZ + 0.2]], 'roof', { origin3: [-0.5, -0.8, hiZ], u3: [0.99, 0, -0.16], v3: [0, 1, 0] });
  m.beam([8.8, -0.8, loZ - 0.2], [8.8, 16.8, loZ - 0.2], 0.25);
  return { svg: m.svg('the shed room seen from its end, its long side running into the screen'), anchorX: f.anchorX, anchorY: f.anchorY, logicalHeight: SHED_LH };
}

function passageFloorEnd() {
  const f = fitted('house-passage-floor-end', boxCorners([0, 0, 0], [12, 16, 1.2]), [12, 0, 0], 8), { m } = f;
  deck(m, [0, 0], [12, 16], 1.1);
  return { svg: m.svg('the passage floor seen end-on, running away from the viewer'), anchorX: f.anchorX, anchorY: f.anchorY, logicalHeight: PASSAGE_FLOOR_LH };
}

/**
 * The passage's roof seen end-on is a stretch of the house's own roof: a dog-run's passage is roofed along the pens' ridge
 * (HIST-GONZ-025), so seen with the pens one behind the other its roof is the join section, twelve feet of it, here on four
 * posts under its eaves (her porch's post wood) for a passage standing on its own.
 */
function passageRoofEnd() {
  const frame = her(JOIN['house-roof-join'].from), wallHigh = PEN.wall * PEN.Z;
  const posts = [];
  // Her roof's eaves from a point on its ridge: the right eave down the joints, the left down-left across the far slope.
  const eaves = (point, s) => { const q = point(s, 0); return { right: [q[0] + JOINT_DIR[0] * 186, q[1] + JOINT_DIR[1] * 186], left: [q[0] - 14, q[1] + 10] }; };
  const post = (c, [x, y]) => {
    const w = 9, top = y - 2, bottom = y + wallHigh - 18, tex = TEXTURES.post, poly = [[x - w / 2, top], [x + w / 2, top], [x + w / 2, bottom], [x - w / 2, bottom]];
    const clip = c.clip(poly), mm = affine(tex.q0, tex.u, tex.v, poly[0], [0, bottom - top], [w, 0]);
    c.raw(`<g clip-path="url(#${clip})"><g transform="matrix(${mm.map(f2).join(' ')})"><image href="${tex.href}" x="0" y="0" width="${tex.sheetW}" height="${tex.sheetH}"/></g></g><polygon points="${P(poly)}" fill="none" stroke="${INK}" stroke-width="${LINE.inner}"/>`);
    posts.push([x, bottom]);
  };
  const drawn = roofJoin('house-passage-roof-end', { span: [0.12, 0.88], bottom: 80,
    under: (c, point, lo, hi) => { for (const s of [hi - 0.35, lo + 0.35]) post(c, eaves(point, s).left); post(c, eaves(point, hi - 0.35).right); },
    over: (c, point, lo) => post(c, eaves(point, lo + 0.35).right) });
  const c = drawn.c, front = [(posts[1][0] + posts[3][0]) / 2, Math.max(posts[1][1], posts[3][1])];
  return { ...drawn, anchorX: +(front[0] / c.w).toFixed(4), anchorY: +(front[1] / c.h).toFixed(4), logicalHeight: Math.round(frame.h * 1.35 / 2.2),
    svg: drawn.svg.replace('one roof section with no gable end and no end pole, to lie between two pens', 'twelve feet of it on four posts: the passage roof seen end-on') };
}

// ---------------------------------------------------------------------------------------------------------------- E5: the saddlebag's rooms
// Two round-log pens wall to wall round one central chimney, a fire-box into each, no passage (sim/houseplot.mjs
// `saddlebag`; HIST-TEX-017), in her `interior-dog-run`'s own camera, scale and cutaway: her dog-run's two pens cut apart
// at the passage and laid the other way round, so each pen's hearth wall - the dog-run's outer ends - meets the other's in
// the middle, the two fire-boxes back to back and their two stacks side by side over the middle as one double chimney.
// The passage and its posts are gone; each pen's passage side becomes the house's end wall. Each pen is seen from its own
// middle (the dog-run's single vanishing point now lies at the outer ends), a storybook cutaway that opens the middle wall
// so both hearths show; a camera at the house's middle would see neither fire-box. Stated, not hidden: the way out is her
// drawing. The spots (sim/interior-data.mjs) are measured on this picture.
const SADDLEBAG = { passage: [300, 458] };

function saddlebagInterior() {
  const f = her('interior-dog-run'), c = new Canvas('interior-saddlebag', f.w, f.h);
  const [cut, back] = SADDLEBAG.passage, lap = 12, west = f.w - back, width = west + cut - lap, ox = Math.round((f.w - width) / 2);
  // The dog-run's east pen, its hearth on its right, becomes the west pen; its west pen, hearth on its left, the east. Each is
  // cut along its passage-side posts (the passage's floor and grass left out) and the two hearth walls overlap a little, so
  // their corner logs stand together as the middle wall and the two stacks as one double chimney.
  const piece = (xs, at) => {
    const clip = c.clip(xs.map(([x, y]) => [at + x, y]));
    c.raw(`<g clip-path="url(#${clip})">${c.image(f, at, 0)}</g>`);
  };
  // Behind both, the one chimney's mass between the two stacks, laid in the stone of her east stack's shaft.
  const x0 = ox - back + 710, x1 = ox + west - lap + 50, top = 24, shaft = [680, 14, 28, 66];
  for (let x = x0; x < x1; x += shaft[2] - 1) for (let y = top; y < 205; y += shaft[3] - 1) {
    const clip = c.clipRect(x, y, Math.min(shaft[2], x1 - x), shaft[3]);
    c.raw(`<g clip-path="url(#${clip})">${c.image(f, x - shaft[0], y - shaft[1])}</g>`);
  }
  c.raw(`<rect x="${x0}" y="${top}" width="${x1 - x0}" height="${205 - top}" fill="none" stroke="${INK}" stroke-width="${LINE.inner}"/>`);
  piece([[back - 2, 0], [f.w, 0], [f.w, f.h], [back + 12, f.h], [back + 8, 170], [back + 2, 60]], ox - back);
  piece([[0, 0], [cut, 0], [cut - 2, 60], [cut - 6, 170], [cut - 10, f.h], [0, f.h]], ox + west - lap);
  return { svg: c.svg('Astra\'s dog-run rooms cut at the passage and laid the other way round: a saddlebag\'s two pens round one central double chimney'),
    // Anchored at the foot of its front logs (the page lays the picture by its own box, public/interior.js, so this moves nothing).
    anchorX: f.anchorX, anchorY: 0.985 };
}

// ---------------------------------------------------------------------------------------------------------------- E7: the loopholed house
// A flat-roofed stone house of Béxar made ready for street fighting, December 1835 (request 2026-09-25, the storming of
// Béxar, item 1; docs/battle-research/staging.md §3.9, HIST-TEX-490 to -496): "a pigeon nursery" (Lopez) - its walls cut
// with loopholes and its parapet raised to about four feet so men could fire from the roof. Made from Astra's `adobe-flat`
// (Béxar's houses were stone or adobe, plastered, flat-roofed behind a parapet): her parapet band laid again above itself so
// it stands about four feet over the roof (her door is about 80 of her pixels for six and a half feet, so a foot is about
// 12), a row of loopholes along it and more beside the door and window, the window shuttered with planks. The number and
// placing of loopholes is not recorded for any one house; these are an interpretation.
// `band` is her parapet's plain plaster (below its top edge's line, above the vigas), laid once more under itself.
const LOOPHOLED = { band: [30, 48], slits: [[62, 42], [104, 42], [152, 42], [206, 42], [252, 42], [34, 98], [146, 104], [228, 104], [254, 120]] };
LOOPHOLED.raise = LOOPHOLED.band[1] - LOOPHOLED.band[0];

function loopholedHouse() {
  const f = her('adobe-flat'), { raise, band } = LOOPHOLED, c = new Canvas('house-loopholed', f.w, f.h + raise);
  // Her roof rim and parapet as they are; the parapet's plaster band once more under them; her house below, lowered.
  const [b0, b1] = band;
  c.raw(`<g clip-path="url(#${c.clipRect(0, b1 + raise, f.w, f.h)})">${c.image(f, 0, raise)}</g>`);
  c.raw(`<g clip-path="url(#${c.clipRect(0, b1, f.w, raise)})">${c.image(f, 0, b1 - b0)}</g>`);
  c.raw(`<g clip-path="url(#${c.clipRect(0, 0, f.w, b1)})">${c.image(f, 0, 0)}</g>`);
  // The window closed with planks nailed across it.
  const [wx, wy, ww, wh] = [172, 94 + raise, 36, 34];
  c.raw(`<rect x="${wx}" y="${wy}" width="${ww}" height="${wh}" fill="#6b4a2c" stroke="${INK}" stroke-width="${LINE.fine + 0.4}"/>`);
  for (let i = 1; i < 4; i++) c.line([[wx + 1, wy + i * wh / 4], [wx + ww - 1, wy + i * wh / 4 + 1]], { width: LINE.fine, colour: '#3a2414' });
  c.line([[wx + 4, wy + 3], [wx + ww - 4, wy + wh - 3]], { width: LINE.inner, colour: '#8a6238' });
  // Loopholes: narrow slits splayed on the outside, dark within.
  for (const [x, y] of LOOPHOLED.slits) {
    const yy = y + (y > band[1] ? raise : 0);
    c.raw(`<path d="M ${x - 3.4} ${yy} L ${x + 3.4} ${yy} L ${x + 2} ${yy + 15} L ${x - 2} ${yy + 15} Z" fill="#b89468" opacity="0.9"/>`);
    c.raw(`<rect x="${x - 1.3}" y="${yy + 1.5}" width="2.6" height="12" rx="1" fill="#1c120b"/>`);
  }
  return { svg: c.svg('Astra\'s adobe-flat with its parapet raised to about four feet and loopholes cut in parapet and walls: a Béxar house held in the storming'),
    anchorX: f.anchorX, anchorY: +((f.anchorY * f.h + raise) / (f.h + raise)).toFixed(4), logicalHeight: f.h };
}

// ---------------------------------------------------------------------------------------------------------------- E13: lit windows
// Lamplight in a window at night (request 2026-09-25, the south's fights, item 2: San Patricio, where local men "left
// lanterns burning in their own windows", FIC-GONZ-435), as overlays registered to her houses: each frame is her house's own
// box, anchor and logical height, clear but for the window, which is filled with warm light (and her mullions where the
// window is glazed). Drawn after the night's wash, so the window is bright in the dark. Openings read on her frames.
const LIT = {
  'adobe-flat': { pane: [176, 95, 27, 31], cross: true },
  'house-jacal': { pane: [184, 98, 24, 22] },
  'jacal-poor': { pane: [71, 99, 22, 21] },
  'cabin-small': { pane: [131, 154, 28, 38], cross: true },
};

function litWindow(house) {
  const f = her(house), { pane: [x, y, w, h], cross } = LIT[house], c = new Canvas(`window-lit-${house}`, f.w, f.h);
  const g = c.id('lamp'), blur = c.id('halo');
  c.defs.push(`<radialGradient id="${g}" cx="0.5" cy="0.6" r="0.7"><stop offset="0" stop-color="#fff1b8"/><stop offset="0.55" stop-color="#ffc867"/><stop offset="1" stop-color="#e08a32"/></radialGradient>`);
  c.defs.push(`<filter id="${blur}" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="4"/></filter>`);
  c.raw(`<rect x="${x - 7}" y="${y - 7}" width="${w + 14}" height="${h + 14}" rx="4" fill="#ffc867" opacity="0.35" filter="url(#${blur})"/>`);
  // Her own window frame round it, so the overlay carries the whole window lit (and matches her picture pixel for pixel).
  c.raw(`<g clip-path="url(#${c.clipRect(x - 5, y - 5, w + 10, h + 10)})">${c.image(f, 0, 0)}</g>`);
  c.raw(`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#${g})"/>`);
  if (cross) {
    c.line([[x + w / 2, y], [x + w / 2, y + h]], { width: LINE.inner, colour: '#3a2414' });
    c.line([[x, y + h / 2], [x + w, y + h / 2]], { width: LINE.inner, colour: '#3a2414' });
  }
  c.raw(`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="none" stroke="#3a2414" stroke-width="${LINE.fine}"/>`);
  return { svg: c.svg(`lamplight in the window of Astra's ${house}, an overlay registered to her frame`), anchorX: f.anchorX, anchorY: f.anchorY, logicalHeight: f.logicalHeight || f.h };
}

const plotFrames = () => [
  { name: 'house-chimney-double', draw: doubleChimney, height: 1.9, compare: [['house-chimney-stone', 2.1 * 1.9 / 2.2], ['house-round-full-walls', 1.9]],
    prompt: 'The saddlebag house\'s double chimney: one broad mass of laid stone filling the eight feet between two log pens\' gable walls, a fire-box opening into each pen (inside, not seen from here), shoulders drawing in to one tall stack with two flues that rises three or four feet over the ridge; corner-on three-quarter view in the log pens\' projection, laid in Astra\'s own stone from her stone chimney, outlined in her ink. Its anchor is the middle of its foot on the pens\' centre line, its four foot corners are given (`foot`). Stone is an interpretation: saddlebag chimneys were stone or stick-and-clay (HIST-TEX-017). Transparent ground, no shadow.' },
  { name: 'house-shed-frame', draw: shedFrame, height: 1.9 * 1.1 / 2.2, compare: [['house-shed-room', 1.9 * 1.1 / 2.2], ['lean-to', 1.9 * 1.1 / 2.2]],
    prompt: 'A shed room framed and not yet boarded, against the back of a log pen: round sills on the ground, corner and middle posts, plates along the tops, rafters of its lean-to roof running from the high back to the low front, sixteen feet long and eight deep, in Astra\'s shed room\'s orientation and size so her finished room replaces it in place; her post wood, outlined in her ink, corner-on three-quarter view. Transparent ground, no shadow.' },
  { name: 'house-floor', draw: penFloor, height: 1.9, compare: [['house-floor-loft', 1.9], ['house-round-sill', 1.9]],
    prompt: 'A puncheon floor for a log pen - split logs hewn flat on one face and laid side by side - as an overlay registered to Astra\'s pen (her full walls\' box, anchor and scale), laid with her own hewn-log faces; drawn before the walls it shows through the doorway and over the low courses. Transparent ground, no shadow.' },
  { name: 'house-loft', draw: penLoft, height: 1.9, compare: [['house-floor-loft', 1.9], ['house-round-full-walls', 1.9]],
    prompt: 'A pen\'s loft as an overlay registered to Astra\'s pen: joists across at the tops of the walls, a floor of boards over the back half (her planks), and a pole ladder up from the floor, for a cutaway; corner-on three-quarter view, her scale, outlined in her ink. Transparent ground, no shadow.' },
];

const endFrames = () => [
  { name: 'house-porch-end', draw: porchEnd, height: 1.9 * 0.9 / 2.2, compare: [['house-porch', 1.9 * 0.9 / 2.2]],
    prompt: 'The porch seen from its narrow end, its long side running into the screen along the pen\'s other diagonal: a plank deck on sills, round posts, a shed roof of clapboards falling from the pen\'s side to the porch\'s edge - Astra\'s porch turned a quarter, built in her pen\'s projection with her own planks, posts and roof boards, outlined in her ink, sized to her porch. Transparent ground, no shadow.' },
  { name: 'house-shed-room-end', draw: shedRoomEnd, height: 1.9 * 1.1 / 2.2, compare: [['house-shed-room', 1.9 * 1.1 / 2.2]],
    prompt: 'The shed room seen from its narrow end, its long side running into the screen: upright boards, a plank door in the end, a lean-to roof of clapboards higher at the pen\'s side - Astra\'s shed room turned a quarter, built in her pen\'s projection with her own boards and roof, outlined in her ink, sized to her shed room. Transparent ground, no shadow.' },
  { name: 'house-passage-floor-end', draw: passageFloorEnd, height: 1.9 * 0.72 / 2.2, compare: [['house-passage-floor', 1.9 * 0.72 / 2.2]],
    prompt: 'The dog-run\'s passage floor seen end-on, running away from the viewer between two pens: a plank deck on sills - Astra\'s passage floor turned a quarter, built with her own planks in her pen\'s projection, sized to hers. Transparent ground, no shadow.' },
  { name: 'house-passage-roof-end', draw: passageRoofEnd, height: 1.9 * 1.35 / 2.2, compare: [['house-passage-roof', 1.9 * 1.35 / 2.2]],
    prompt: 'The passage roof on its four posts seen end-on: its ridge running across the screen, the clapboard slope toward the viewer, the gable end on the right open under its boards - Astra\'s passage roof turned a quarter, in her pen\'s projection with her own roof boards and posts, sized to hers. Transparent ground, no shadow.' },
];

// ---------------------------------------------------------------------------------------------------------------- sheets
const request = { sides: 'Request 2026-09-23 — the house from its other sides', roof: 'Request 2026-09-24 — one roof over a two-pen house', plot: 'Request 2026-09-15 — the house plot\'s pieces' };
const cellOf = names => ({ w: Math.max(...names.map(n => her(n).w)), h: Math.max(...names.map(n => her(n).h)) });

export const SHEETS = {
  'claude-house-back': { cell: { w: 320, h: 270 }, columns: 3, request: request.sides,
    replaceWith: 'the pen from behind: the gable toward the viewer without its door, in the house-modules style, scale and corner-on view, with its anchor, seat and ground corners',
    frames: backFrames() },
  'claude-house-roof-join': { cell: { w: 404, h: 299 }, columns: 3, request: request.roof,
    replaceWith: 'the roof over the passage between two pens at exactly the pens\' pitch, ridge and eaves, with no gable ends and no end poles; the ridge line marked',
    frames: [...joinFrames(), { name: 'house-roof-join-chimney', draw: roofJoinChimney, height: 1.9, compare: [['house-hewn-roof-finished', 1.9], ['house-chimney-stone', 1.8]],
      prompt: 'The roof section between a saddlebag house\'s two pens, drawn so its double chimney stands through the ridge: Astra\'s finished roof\'s middle repeated along its ridge (as house-roof-join), with an opening cut where the chimney\'s stack rises above the right slope, so the chimney drawn before it shows through and the boards in front of its foot stay. Carries where the chimney\'s foot is (`chimneyAt`) and its ridge (`ridge`). Corner-on three-quarter view, her pitch, eaves, scale and outline. Transparent ground.' }] },
  'claude-house-jacal': { cell: { w: 382, h: 303 }, columns: 3, request: request.plot,
    replaceWith: 'jacal modules - posts, wattle and daub walls, thatch - in the house-modules style, stage by stage, with anchors, seats and ground corners',
    frames: jacalFrames() },
  'claude-house-plot': { cell: { w: 330, h: 345 }, columns: 2, request: request.plot,
    replaceWith: 'the remaining house-plot pieces in the house-modules style: the double chimney two-sided with its foot marked, the shed frame, separate floor and loft overlays',
    frames: plotFrames() },
  'claude-interior-saddlebag': { cell: { w: 750, h: 331 }, request: 'Request 2026-09-12 (second) — settling in: houses, interiors, furnishings, and people whose looks can be chosen',
    replaceWith: 'a saddlebag interior in the home-interiors style, camera and scale exactly as interior-dog-run: two round-log pens wall to wall round one central stone chimney, a fireplace into each, no passage',
    frames: [{ name: 'interior-saddlebag', draw: saddlebagInterior, compare: [['interior-dog-run', 3]], height: 3,
      prompt: 'The rooms of a saddlebag house, cut away as Astra\'s interior-dog-run is and in exactly its camera and scale: two round-log pens wall to wall, a stone fireplace in the middle wall of each, their two stacks side by side over the middle as one double chimney, a window in each back wall, earth floors, no passage. Made from her own dog-run rooms cut at the passage and laid the other way round (each pen seen from its own middle, a cutaway convention that opens the middle wall so both hearths show). Saddlebag houses had one central chimney serving both pens (HIST-TEX-017). Transparent background.' }] },
  'claude-house-loopholed': { cell: { w: 296, h: 204 }, request: 'Request 2026-09-25 — the storming of Béxar',
    replaceWith: 'item 1: a flat-roofed stone house, a parapet about four feet high, loopholes in its walls, at the stone-tile-house scale',
    frames: [{ name: 'house-loopholed', draw: loopholedHouse, height: 2.4, compare: [['adobe-flat', 2.4], ['stone-tile-house', 2.4], ['volunteer-e', 1]],
      prompt: 'A flat-roofed Béxar house held in the street fighting of December 1835 ("a pigeon nursery", Lopez; HIST-TEX-490 to -496): Astra\'s plastered adobe-flat with its parapet raised to about four feet over the roof for men to fire from, loopholes - narrow slits splayed outside - cut along the parapet and beside the door and window, the window shuttered with planks nailed across. The number and placing of the loopholes is an interpretation; Béxar\'s houses were stone or adobe, plastered, flat-roofed. Her frontal three-quarter view, scale and outline. Transparent ground, no shadow.' }] },
  'claude-window-lit': { cell: { w: 300, h: 250 }, columns: 4, request: 'Request 2026-09-25 — the south\'s fights: San Patricio by night and Agua Dulce Creek',
    replaceWith: 'item 2: a lit-window overlay registered to the building it overlays',
    frames: Object.keys(LIT).map(house => ({ name: `window-lit-${house}`, draw: () => litWindow(house), height: 2.4, compare: [[house, 2.4]],
      prompt: `Lamplight in the window of Astra's ${house} at night: an overlay in her frame's own box, anchor and logical height, clear except the window, filled with a warm lamp glow (pale yellow at the middle to orange at the edges) with a soft halo${LIT[house].cross ? ' and her dark mullions across it' : ''}; laid over her house after the night's darkness so the window shines. San Patricio, February 1836: local men left lanterns burning in their own windows (FIC-GONZ-435). Transparent elsewhere.` })) },
  'claude-house-ends': { cell: { w: 404, h: 380 }, columns: 2, request: request.sides,
    replaceWith: 'the passage, porch and shed room seen from their narrow ends, their long side running into the screen, in the house-modules style and scale',
    frames: endFrames() },
};

// Frames are drawn in their own box (her frame's size) and the sheet's cell is the largest of them: pad each SVG to the cell.
for (const spec of Object.values(SHEETS)) {
  for (const frame of spec.frames) {
    const draw = frame.draw;
    frame.draw = () => padTo(draw(), spec.cell);
  }
}

/** Put a frame drawn in its own w x h box at the top left of a larger cell, and move its fractions to the cell. */
function padTo(drawn, cell) {
  const m = drawn.svg.match(/viewBox="0 0 (\d+(?:\.\d+)?) (\d+(?:\.\d+)?)"/);
  const w = +m[1], h = +m[2];
  if (w === cell.w && h === cell.h) return drawn;
  if (w > cell.w || h > cell.h) throw new Error(`house-pieces: a ${w}x${h} frame does not fit its ${cell.w}x${cell.h} cell`);
  // Anchored at the bottom of the cell so the ground sits low, centred across.
  const ox = Math.round((cell.w - w) / 2), oy = cell.h - h;
  const fx = x => +((ox + x * w) / cell.w).toFixed(4), fy = y => +((oy + y * h) / cell.h).toFixed(4);
  const svg = drawn.svg.replace(`width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"`, `width="${cell.w}" height="${cell.h}" viewBox="0 0 ${cell.w} ${cell.h}"`)
    .replace(/<g>/, `<g transform="translate(${ox} ${oy})">`)
    .replace(/<defs>/, `<defs>`);
  // clipPaths are in user space of the element they apply to: they sit inside the translated group, so they move with it.
  const out = { ...drawn, svg, anchorX: fx(drawn.anchorX), anchorY: fy(drawn.anchorY),
    // The picture keeps its pixel scale: the logical height is still that of the frame of hers it goes with.
    logicalHeight: drawn.logicalHeight };
  if (drawn.seat) out.seat = [fx(drawn.seat[0]), fy(drawn.seat[1])];
  if (drawn.ground) out.ground = Object.fromEntries(Object.entries(drawn.ground).map(([k, [x, y]]) => [k, [fx(x), fy(y)]]));
  if (drawn.extra?.ridge) out.extra = { ...drawn.extra, ridge: drawn.extra.ridge.map(([x, y]) => [fx(x), fy(y)]) };
  return out;
}
