// Scenery composed from Astra's own trees, area F (docs/CLAUDE_ART_PLAN.md): a live-oak mott as one sprite with the shade
// under it (F10, request 2026-09-25 — the south's fights, item 5) and a hardwood going over when it is felled (F3, request
// 2026-09-28 — people at work, item 15, `tree-fall`). Her painted `live-oak-large`, `live-oak-log` and `post-oak-log` are
// embedded at 1:1 and placed, turned and shaded by Claude (the shade, the dust and the flying leaves drawn by Claude); so the
// trees are hers and at her scale, and the arrangement is the stand-in.
import { astraFrame } from '../land/pixels.mjs';
import { cached, hashOf, codeOf, astraImage } from '../land/embed.mjs';
import { billow, rng, f1 } from '../land/paint.mjs';

export const AREA = 'land';
export const DATE = '2026-09-28';
const MODULE = 'land-scenery';
const SOUTH = "Request 2026-09-25 — the south's fights: San Patricio by night and Agua Dulce Creek";
const WORK = 'Request 2026-09-28 — people at work';
const CODE = codeOf('./embed.mjs', './pixels.mjs', './paint.mjs', '../areas/land-scenery.mjs');
const head = (name, w, h, note) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <!-- ${name}: ${note}
       Claude-drawn stand-in (temporary: replace with Astra's ${name}). Generated by scripts/claude-art/areas/${MODULE}.mjs; do not hand-edit. -->
`;

// ---- the mott ------------------------------------------------------------------------------------------------------------
// A mott is a close grove of live oaks standing in open grass - on the coastal sand plain and at Agua Dulce Creek (docs/
// BIOMES.md §4.10; the south's fights). Four of her live oaks, two at the back set up the screen and a shade darker, two in
// front, over a pool of shade on the grass under their crowns. The frame's logical height is her `live-oak-large`'s, so drawn
// at the height the page gives one live oak the mott's trees are that size.
const MOTT = { w: 760, h: 360, gy: 340 };
const MOTT_TREES = [
  { tree: 'live-oak-log', x: 190, back: 34, flip: true, dark: true },
  { tree: 'live-oak-large', x: 470, back: 40, flip: false, dark: true },
  { tree: 'live-oak-large', x: 300, back: 6, flip: false },
  { tree: 'live-oak-log', x: 560, back: 0, flip: true },
];
function mott() {
  const name = 'live-oak-mott';
  const key = hashOf(CODE, MOTT, MOTT_TREES, ...MOTT_TREES.map(t => astraFrame(t.tree).sha));
  const svg = cached(MODULE, name, key, () => {
    const images = {};
    for (const t of MOTT_TREES) images[t.tree] ??= astraImage(t.tree, { keepBelow: 8 });
    const parts = [`<defs><filter id="${name}-back" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="0.8 0 0 0 0  0 0.84 0 0 0  0 0 0.84 0 0  0 0 0 1 0"/></filter>`];
    for (const [tree, im] of Object.entries(images)) parts.push(`<image id="${name}-${tree}" width="${im.w}" height="${im.h}" href="${im.href}"/>`);
    parts.push('</defs>');
    // The shade on the grass under the crowns: darker in the middle, soft at its edge, all of it above the front trees' feet.
    parts.push(`<defs><radialGradient id="${name}-shade"><stop offset="0" stop-color="#2b3518" stop-opacity="0.55"/><stop offset="0.7" stop-color="#34401d" stop-opacity="0.35"/><stop offset="1" stop-color="#34401d" stop-opacity="0"/></radialGradient></defs>`);
    parts.push(`<ellipse cx="${f1(MOTT.w / 2 + 10)}" cy="${MOTT.gy - 26}" rx="330" ry="34" fill="url(#${name}-shade)"/>`);
    for (const t of MOTT_TREES) {
      const im = images[t.tree], y = MOTT.gy - t.back - im.gy, x = t.x - (t.flip ? im.w - im.ax : im.ax);
      const place = t.flip ? `translate(${f1(x + im.w)} ${f1(y)}) scale(-1 1)` : `translate(${f1(x)} ${f1(y)})`;
      parts.push(`<use href="#${name}-${t.tree}" transform="${place}"${t.dark ? ` filter="url(#${name}-back)"` : ''}/>`);
    }
    return `${head(name, MOTT.w, MOTT.h, 'a live-oak mott: four of Astra\'s live oaks set close over the shade under their crowns')}  <g>${parts.join('')}</g>\n</svg>\n`;
  });
  return { svg, anchorX: 0.5, anchorY: +(MOTT.gy / MOTT.h).toFixed(4), logicalHeight: astraFrame('live-oak-large').h };
}

// ---- the tree going over -------------------------------------------------------------------------------------------------
// Her `post-oak-log` (a hardwood of log size) turning about the foot of its trunk: leaning, going over, down, and a last
// bounce as the crown comes to rest. It falls away to the right, into the scene, so the fallen crown lies up the screen and is
// foreshortened (squashed) the further over it is; dust thrown up and leaves shaken loose as it lands.
const FALL = { w: 640, h: 360, gy: 336, px: 150 };
const FALL_POSES = [{ turn: 9, squash: 1 }, { turn: 32, squash: 0.92 }, { turn: 55, squash: 0.54, dust: 1 }, { turn: 51, squash: 0.58, dust: 0.6, lift: 4 }];
function treeFall(i) {
  const name = `tree-fall-${i + 1}`, pose = FALL_POSES[i];
  const key = hashOf(CODE, FALL, pose, astraFrame('post-oak-log').sha);
  const svg = cached(MODULE, name, key, () => {
    const im = astraImage('post-oak-log', { keepBelow: -6 });
    const R = rng(700 + i), parts = [];
    // Turned about the trunk's foot, squashed toward the ground as it lies over into the scene.
    const pivotY = FALL.gy - 6 - (pose.lift || 0);
    parts.push(`<g transform="translate(${FALL.px} ${f1(pivotY)}) scale(1 ${pose.squash}) rotate(${pose.turn}) translate(${f1(-im.ax)} ${f1(-(im.gy - 6))})"><image width="${im.w}" height="${im.h}" href="${im.href}"/></g>`);
    // The torn hinge of the cut at the foot.
    parts.push(`<path d="M ${FALL.px - 16} ${FALL.gy - 4} l 6 -9 l 5 5 l 6 -8 l 5 7 l 6 -6 l 4 11 Z" fill="#e2c08a" stroke="#23180f" stroke-width="1.4"/>`);
    if (pose.dust) {
      for (let k = 0; k < 5; k++) parts.push(billow(R, FALL.px + 70 + k * 42, FALL.gy - 10 - R() * 8, 13 + R() * 10, { fill: '#c9b08a', lobes: 7, outline: 1.3, alpha: pose.dust }));
      for (let k = 0; k < 8; k++) { const x = FALL.px + 60 + R() * 220, y = FALL.gy - 120 - R() * 90, s = 4 + R() * 3; parts.push(`<ellipse cx="${f1(x)}" cy="${f1(y)}" rx="${f1(s)}" ry="${f1(s * 0.5)}" transform="rotate(${f1(R() * 180)} ${f1(x)} ${f1(y)})" fill="#7f9446" stroke="#1f2412" stroke-width="0.7"/>`); }
    }
    return `${head(name, FALL.w, FALL.h, `a felled hardwood going over, frame ${i + 1} of 4`)}  <g>${parts.join('')}</g>\n</svg>\n`;
  });
  // Drawn at a person's height by public/app.js (`treesFalling`), where a -log tree is 1.95 x 0.7 of a person tall.
  return { svg, anchorX: +(FALL.px / FALL.w).toFixed(4), anchorY: +(FALL.gy / FALL.h).toFixed(4), logicalHeight: Math.round(astraFrame('post-oak-log').h / (1.95 * 0.7)) };
}

export const SHEETS = {
  'claude-live-oak-mott': { cell: { w: MOTT.w, h: MOTT.h }, columns: 1, request: SOUTH, replaceWith: 'item 5: a live-oak mott as one sprite with the shade under it, anchored at its base, at the scale of the live oaks it stands beside',
    frames: [{ name: 'live-oak-mott', height: 3.2, compare: [['live-oak-large', 3.2], ['mesquite-large', 3.2]], draw: mott,
      prompt: 'A live-oak mott at Agua Dulce Creek and on the coastal sand plain: four live oaks growing close together in open grass - two at the back set a little up the screen and a shade darker, two in front - over a pool of shade on the grass under their low wide crowns. Astra\'s own live-oak-large and live-oak-log paintings, placed and shaded by Claude, at her scale; transparent ground beyond the shade, no text.' }] },
  'claude-tree-fall': { cell: { w: FALL.w, h: FALL.h }, columns: 2, request: WORK, replaceWith: 'item 15: tree-fall, 4 frames on the stump\'s ground anchor - a hardwood of -log size leaning, going over, down, a last bounce',
    frames: FALL_POSES.map((pose, i) => ({ name: `tree-fall-${i + 1}`, height: 1, compare: [['post-oak-log', 1.95 * 0.7], ['stump-post-oak', 1]], draw: () => treeFall(i),
      prompt: `A felled hardwood going over, frame ${i + 1} of 4 (${['leaning as the hinge gives', 'going over', 'down on the ground, dust thrown up and leaves shaken loose', 'the last bounce as the crown settles'][i]}): Astra's own post-oak-log painting turned about the foot of its trunk and falling away to the right into the scene, the fallen crown foreshortened; the torn pale hinge of the cut at the foot; Claude's dust and leaves. Her scale, anchored at the stump; transparent ground.` })) },
};
export const CLIPS = {
  'tree-fall': { frames: [520, 240, 160, 320].map((duration, i) => ({ sprite: `tree-fall-${i + 1}`, duration })), loop: false, motion: 'none', direction: 'east; west by mirroring',
    prompt: 'A felled hardwood going over once where it was cut: leaning (held), going over, down in a cloud of dust, a last bounce; timed as area A timed it with the fall the audio hears.' },
};
