// Write docs/CLAUDE_ART_PLAN.md and the "What Astra still needs to make" section of docs/ART_REQUESTS.md from
// scripts/claude-art/plan.mjs and the Claude manifest. Both are generated so they stay in step: an item whose Claude
// stand-in lands is marked on both at once, and stays on Astra's list. tests/claude-standins.test.mjs fails if either is stale.
//
// Run: node scripts/claude-art/write-plan.mjs   (after npm run build:standins, so the manifest is current)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { AREAS, ITEMS, claudeFor } from './plan.mjs';

const DOCS = fileURLToPath(new URL('../../docs/', import.meta.url));
export const PLAN_FILE = DOCS + 'CLAUDE_ART_PLAN.md';
export const REQUESTS_FILE = DOCS + 'ART_REQUESTS.md';
export const START = '<!-- astra-list:start (generated by scripts/claude-art/write-plan.mjs from scripts/claude-art/plan.mjs; do not hand-edit) -->';
export const END = '<!-- astra-list:end -->';
const KIND = { library: 'Astra\'s library art reused', code: 'drawn in code (canvas or CSS)', words: 'told in words, not drawn', claude: 'Claude-drawn', none: 'nothing' };

/** GitHub's heading anchor. */
export const slug = heading => '#' + heading.toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu, '').replace(/\s/g, '-');
const open = item => item.status === 'open';
const byPriority = (a, b) => a.priority - b.priority || a.id.localeCompare(b.id, 'en', { numeric: true });

function claudeNote(item, manifest) {
  const drawn = claudeFor(item, manifest);
  return drawn.length ? `**Claude stand-in in place** (${drawn.map(n => `\`${n}\``).join(', ')}); Astra's replaces it` : '';
}

/** The section of ART_REQUESTS.md, between the markers. */
export function astraSection(manifest) {
  const lines = [START, '## What Astra still needs to make: every stand-in and what replaces it', '',
    'Owner, 2026-09-28: *"add to the art requests list which items need to be made so they can replace stand ins."* One checklist of every item that must be made to retire a stand-in: every row of *Stand-ins in use*, every row of *Claude-drawn stand-ins*, and every `stand-in:` comment in the code (`public/`, `sim/`). It is generated with [CLAUDE_ART_PLAN.md](CLAUDE_ART_PLAN.md) from one table, `scripts/claude-art/plan.mjs`, grouped by the same areas and sorted by priority (1 first). An item whose Claude-drawn stand-in has landed **stays here** - hers replaces it - marked *Claude stand-in in place*. `tests/claude-standins.test.mjs` fails if a `stand-in:` in the code names nothing on this list, and if this section is stale (`node scripts/claude-art/write-plan.mjs`).', ''];
  const openItems = ITEMS.filter(open);
  lines.push(`**${openItems.length} items to make** (${Object.keys(AREAS).map(a => `${a} ${openItems.filter(i => i.area === a).length}`).join(', ')}); ${openItems.filter(i => claudeFor(i, manifest).length).length} with a Claude stand-in in place. Delivered, withdrawn and on-hold requests are listed after them, with nothing to make.`, '');
  for (const [key, area] of Object.entries(AREAS)) {
    const items = openItems.filter(i => i.area === key).sort(byPriority);
    lines.push(`### ${key} — ${area.title} (${items.length})`, '');
    for (const item of items) {
      const note = claudeNote(item, manifest);
      lines.push(`- [ ] **${item.id}** · priority ${item.priority} · ${item.deliver}. *${item.frames}*. ${item.size}. [${item.request.replace(/\*\*/g, '')}](${slug(item.request)})${item.item ? `, ${item.item}` : ''}. **Stands in now:** ${item.standIn} (${KIND[item.kind]}). **Plugs into:** ${item.plugs}.${item.research ? ` **Research:** ${item.research}.` : ''}${note ? ` ${note}.` : ''}`);
    }
    lines.push('');
  }
  lines.push('### Nothing to make: delivered, withdrawn or on hold', '');
  for (const item of ITEMS.filter(i => !open(i)).sort((a, b) => a.area.localeCompare(b.area) || byPriority(a, b))) {
    lines.push(`- ~~${item.id}~~ [${item.request.replace(/\*\*/g, '')}](${slug(item.request)})${item.item ? `, ${item.item}` : ''} - ${item.status}.`);
  }
  lines.push('', END);
  return lines.join('\n');
}

export function planDoc(manifest) {
  const openItems = ITEMS.filter(open);
  const lines = ['# The Claude art plan', '',
    'Owner, 2026-09-28: *"Astra wrote this so that you can help make art. make all of the remaining art. yours will be temporary. label yours so astra can replace as it makes the final versions."* Her brief is [ART_STYLE.md](ART_STYLE.md). This is every open art item, divided into six areas small enough for one builder each, with what to deliver, at what size, where it plugs in and how urgent it is. The same table (`scripts/claude-art/plan.mjs`) writes *What Astra still needs to make* in [ART_REQUESTS.md](ART_REQUESTS.md): everything drawn here is temporary, and each item stays on her list after Claude\'s version lands.', '',
    '**Generated.** Edit `scripts/claude-art/plan.mjs` and run `node scripts/claude-art/write-plan.mjs`; the status column is read from the Claude manifest, so an item is marked *Claude stand-in in place* the moment its frames are built. `npm test` fails on a stale copy.', '',
    '## Summary', '', '| Area | Items to make | Priority 1 | With a Claude stand-in | Skipped |', '| --- | ---: | ---: | ---: | ---: |'];
  for (const [key, area] of Object.entries(AREAS)) {
    const mine = ITEMS.filter(i => i.area === key), o = mine.filter(open);
    lines.push(`| ${key} — ${area.title} | ${o.length} | ${o.filter(i => i.priority === 1).length} | ${o.filter(i => claudeFor(i, manifest).length).length} | ${mine.length - o.length} |`);
  }
  lines.push(`| **Total** | **${openItems.length}** | **${openItems.filter(i => i.priority === 1).length}** | **${openItems.filter(i => claudeFor(i, manifest).length).length}** | **${ITEMS.length - openItems.length}** |`, '');
  lines.push('## How a builder works', '',
    '1. **Start from the kit.** `scripts/claude-art/kit/`: `style.mjs` (the palette, line and geometry measured from Astra\'s `civilians`, `people-walk` and `people-vertical` by `measure-style.mjs`), `svg.mjs` (outline, flat shade, frame wrapper), `rig.mjs` (the person rig: every cast figure, the children and four generic figures, posed by joints with IK), `poses.mjs` (the pose library), `horse.mjs` (the horse and `mountedFrame`), `props.mjs` (tools and props). `node scripts/claude-art/proof-rig.mjs <figure>` draws every pose of a figure beside Astra\'s own (docs/evidence/claude-art/rig-<figure>.png).',
    '2. **Add your own area module**, `scripts/claude-art/areas/<name>.mjs`, exporting `AREA` (your letter\'s key: `work`, `children`, `battles`, `transport`, `places`, `land`), `DATE`, `SHEETS` and `CLIPS` - see `chop.mjs` (a four-frame clip from the rig) and `wood-pile.mjs` (a procedural prop) - with a written `prompt` for every frame and clip (it is the provenance), and `compare` naming the Astra frames it is judged beside. Never edit another builder\'s module or a shared list: the build finds modules by reading the folder.',
    '3. **Name frames and clips exactly as the request asks** (`<figure>-<pose>-<n>`, clip `<figure>-<pose>`), so the game\'s own clip name picks up the stand-in and Astra\'s of the same name replaces it. A clip is declared as hers are in `animation.json` (frames with durations, `loop`, `motion`, `direction`), plus `beat` for the frame a tool lands on.',
    '4. **Build and look.** `npm run build:standins -- --only <name>` renders your sheets, writes `public/assets/claude-standins/areas/<name>.json` and merges `atlas.json` and `docs/claude-art-provenance.json`. `node scripts/claude-art/compare.mjs <name>` draws your frames beside hers at 40, 77 and 150 px on the map\'s grass (docs/evidence/claude-art/compare-<name>.png). Look at it before you commit.',
    '5. **Wire it only where the game does not already ask for the name.** Most items plug in with no code: the renderer asks for `<figure>-<pose>` and art.js lets a Claude clip fill the gap. Where the code still draws a stand-in of its own (a canvas tool, a `log-fallen` row), switch it the way `STROKES.chop.drawn` and the wood pile in `drawWorld` do - per figure, falling back when the sheet has not loaded - and keep a `stand-in:` comment naming the request and *Claude-drawn stand-ins*.',
    '6. **Record it.** Add your names to your area\'s row of *Claude-drawn stand-ins* in ART_REQUESTS.md (one row an area: nobody else edits it), and rerun `node scripts/claude-art/write-plan.mjs` so this plan and Astra\'s list mark the item. `npm test` (`tests/claude-standins.test.mjs`) fails on a frame without provenance, `madeBy`, a row, or a list item.',
    '7. **After a merge** of two builders\' branches, take either side of a conflict in `public/assets/claude-standins/atlas.json`, `docs/claude-art-provenance.json`, `docs/CLAUDE_ART_PLAN.md` or the generated section of ART_REQUESTS.md, then `npm run build:standins -- --merge` and `node scripts/claude-art/write-plan.mjs`: they are pure functions of the per-module files.', '',
    '**Sizes at a glance.** A person is drawn so that the logical height (300 source px in Claude\'s people frames) is the height the game asks for; the ground is 0.945 of it; `personFrame` makes a 400×400 cell with the ground at y 372 and room for a raised tool. Soldiers use their own longer build (`BUILD.soldier`), as her military atlases do; the baby its own small drawing (`INFANT_POSES`). A mounted frame is 1.8 of a person (`mountedFrame`, logical 540). A prop or building carries its own `logicalHeight` for the height the page draws it at (the wood pile: 1.2 of a person). Icons are 128×128 and marks 96×96, drawn in pixels.', '',
    '**Honest limits.** The rig reads as the same person as Astra\'s figure at play size by silhouette, palette and costume; at 150 px it is plainly a different, simpler hand (thinner limbs, flatter shading, less weight in the poses). Famous people are original interpretations, never likenesses; nothing gory; Texas 1835 tools only.', '');
  for (const [key, area] of Object.entries(AREAS)) {
    const mine = ITEMS.filter(i => i.area === key);
    lines.push(`## ${key} — ${area.title}`, '', `Scope: ${area.scope}. ${mine.filter(open).length} to make, ${mine.filter(i => !open(i)).length} skipped.`, '');
    for (const item of mine.filter(open).sort(byPriority)) {
      const note = claudeNote(item, manifest);
      lines.push(`- [ ] **${item.id}** (priority ${item.priority}) — [${item.request.replace(/\*\*/g, '')}](ART_REQUESTS.md${slug(item.request)})${item.item ? `, ${item.item}` : ''}${note ? ` — ${note}` : ''}`,
        `  - **Deliver:** ${item.deliver}`, `  - **Frames:** ${item.frames}. **Size:** ${item.size}`, `  - **Plugs into:** ${item.plugs}`,
        `  - **Stands in now:** ${item.standIn} (${KIND[item.kind]})`, ...(item.research ? [`  - **Research first:** ${item.research}`] : []));
    }
    const skipped = mine.filter(i => !open(i));
    if (skipped.length) {
      lines.push('', 'Skipped:');
      for (const item of skipped) lines.push(`- ~~${item.id}~~ [${item.request.replace(/\*\*/g, '')}](ART_REQUESTS.md${slug(item.request)}) — ${item.status}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/** ART_REQUESTS.md with its generated section replaced (or inserted after "Standard practice for missing art"). */
export function withSection(text, manifest) {
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const section = astraSection(manifest).split('\n').join(eol);
  const a = text.indexOf(START.slice(0, 24)), b = text.indexOf(END);
  if (a >= 0 && b > a) return text.slice(0, a) + section + text.slice(b + END.length);
  const at = text.indexOf('## Stand-ins in use');
  return text.slice(0, at) + section + eol + eol + text.slice(at);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const manifest = JSON.parse(readFileSync(fileURLToPath(new URL('../../public/assets/claude-standins/atlas.json', import.meta.url)), 'utf8'));
  writeFileSync(PLAN_FILE, planDoc(manifest) + '\n');
  writeFileSync(REQUESTS_FILE, withSection(readFileSync(REQUESTS_FILE, 'utf8'), manifest));
  const openItems = ITEMS.filter(open);
  console.log(`docs/CLAUDE_ART_PLAN.md and ART_REQUESTS.md: ${openItems.length} items to make, ${ITEMS.length - openItems.length} skipped`);
}
