const variants = ['rust-woman','indigo','ochre','blue-girl'];
export const SHEETS = {
  'people-cast2-carry': variants.flatMap(variant => [`${variant}-carry-1`,`${variant}-carry-2`,`${variant}-carry-3`,null]),
};
export const ANIMATION_CLIPS = Object.fromEntries(variants.map(variant => [`${variant}-carry`, {
  frames:[1,2,3,2].map(frame => ({sprite:`${variant}-carry-${frame}`,duration:190})), loop:true, authored:true,
  motion:'none', direction:'east; west by mirroring',
}]));
const prompt = 'Use case: production sprite atlas for a top-down three-quarter-view historical game. Genuine transparent-background 4 by 4 PNG sprite sheet, exactly sixteen complete isolated full-body figures, equal cells, generous gutters, no overlap, no grid, checkerboard, text, ground, shadows, scenery, or extra people. Preserve the four identities and clean dark outlined rustic illustrated style exactly from the reference: row 1 rust-blouse bonneted adult woman; row 2 indigo-dress adult woman; row 3 ochre-shirt young man; row 4 blue-dress adolescent girl. All face EAST/screen-right. Each row is a four-frame carry-walk cycle with the SAME plain tied burlap provisions sack held securely in both arms against the torso: column 1 left foot forward; column 2 passing; column 3 right foot forward; column 4 opposite passing, with visible alternating legs and body motion while the sack remains stable. Maintain identical character head size, clothing, palette, baseline and scale. No floating objects and no different cargo per row. Square PNG with real alpha transparency.';
export const promptEntries = [{sheet:'people-cast2-carry',promptId:'frontier-v1/people-cast2-carry',tool:'built-in image_gen.imagegen',mode:'generate',prompt,referenced_image_paths:['C:/Users/zachw/Texas Civilization/public/assets/frontier-v1/atlases/people-cast2-idle.png'],generatedSourcePath:'C:/Users/zachw/.codex/generated_images/01a082eb-77f7-7f73-8400-ebcc7426ac7b/exec-4fa0e913-f60c-4458-bb82-deeb86e7efe1.png',runtimeFile:'public/assets/frontier-v1/atlases/people-cast2-carry.png',postProcessing:'None. Generated PNG copied unchanged; only read-only validation.',review:'Accepted columns 1-3 as east-facing identity-consistent carry poses. Column 4 is deliberately excluded because two rows turn away from east; clips return through pose 2 rather than using incorrect directional art.'}];
export const provenanceEntries = promptEntries.map(({prompt,...entry})=>entry);
export const notes = ['Second-cast carrying delivered as 12 accepted frames and four 1-2-3-2 authored cycles. Four generated turn-away cells are excluded rather than mislabeled.'];
