// Small painted shapes for area F's effects, in the manner of Astra's `effects` sheet (smoke-small .. smoke-dispersing,
// dust, water-ripple, campfire): billows built of overlapping round lobes under one dark outline, lit to the upper left
// with a paler lift and shaded to the lower right; chips and clods as small outlined solids. Units are source pixels, y down.
import { rng, shade, f1 } from './tree.mjs';

export const INK = '#23180f';
export { rng, shade, f1 };

/**
 * A billow: `lobes` round lobes about (x, y) within radius r, drawn under one outline (each lobe stroked wide in the ink,
 * then all filled), the lit lobes paler toward the upper left. `alpha` fades the whole billow (a thinning puff).
 */
export function billow(R, x, y, r, { fill, lobes = 7, outline = 1.6, alpha = 1, squash = 0.85, lift = 0.28, ink = INK } = {}) {
  const parts = [], ls = [];
  for (let i = 0; i < lobes; i++) {
    const a = (i / lobes) * Math.PI * 2 + R() * 0.5, d = r * (0.3 + R() * 0.28);
    ls.push([x + Math.cos(a) * d, y + Math.sin(a) * d * squash, r * (0.42 + R() * 0.2)]);
  }
  ls.push([x, y, r * 0.55]);
  const circles = (dx, dy, k, colour, extra = 0) => ls.map(([lx, ly, lr]) => `<circle cx="${f1(lx + dx)}" cy="${f1(ly + dy)}" r="${f1(Math.max(0.5, lr * k + extra))}" fill="${colour}"/>`).join('');
  if (outline) parts.push(circles(0, 0, 1, ink, outline));
  parts.push(circles(0, 0, 1, shade(fill, -0.18)));
  parts.push(circles(-r * 0.1, -r * 0.12, 0.8, fill));
  parts.push(circles(-r * 0.2, -r * 0.24, 0.42, shade(fill, lift)));
  return `<g${alpha < 1 ? ` opacity="${f1(alpha * 100) / 100}"` : ''}>${parts.join('')}</g>`;
}

/** A small outlined solid: a chip, a clod, a curl's body. `pts` are corners about (0, 0), turned by `turn` degrees. */
export function solid(x, y, pts, fill, turn = 0, outline = 1.1) {
  return `<path transform="translate(${f1(x)} ${f1(y)}) rotate(${f1(turn)})" d="M ${pts.map(p => `${f1(p[0])} ${f1(p[1])}`).join(' L ')} Z" fill="${fill}" stroke="${INK}" stroke-width="${outline}" stroke-linejoin="round"/>`;
}

/** An SVG frame document for a generated area F frame, with the header every Claude frame carries. */
export function frameDoc(name, w, h, note, body, module) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <!-- ${name}: ${note}
       Claude-drawn stand-in (temporary: replace with Astra's ${name}). Generated by scripts/claude-art/areas/${module}.mjs; do not hand-edit. -->
  <g stroke-linejoin="round" stroke-linecap="round">${body}</g>
</svg>
`;
}
